const { withAppDelegate } = require('@expo/config-plugins');

/**
 * withTwilioVoipPushRegistry
 * --------------------------
 * Owns the app's single VoIP `PKPushRegistry` natively, from process launch,
 * so an incoming call survives a cold launch from a terminated state AND the
 * Twilio React-Native SDK still receives its device token reliably.
 *
 * The device-token half (cache + re-emit) is unchanged and load-bearing — see
 * the long history below. The INCOMING-PUSH half now has a cold-launch path.
 *
 * ── Cold-launch CallKit crash (Jul 2026, build 72, client) ──────────────────
 * iOS's PushKit contract: after `didReceiveIncomingPushWith` you MUST call
 * `CXProvider.reportNewIncomingCall` BEFORE `completion()` returns, in the same
 * run loop, or iOS TERMINATES the app (`_terminateAppIfThereAreUnhandledVoIPPushes`
 * → NSInternalInconsistencyException) AND, on repeat offenses, stops delivering
 * VoIP pushes entirely. The Twilio RN module is the sole reporter, but it is a
 * lazily-instantiated TurboModule whose CXProvider is built in `-init` (~3s after
 * the JS bridge boots). On a fully-killed cold launch the module does not exist,
 * so the old "post the notification and re-post every 0.5s" loop NEVER got a
 * report and eventually called `completion()` bare → the crash (confirmed dual
 * source: Sentry + PostHog, see project_twilio_coldlaunch_callkit).
 *
 * The fix (adversarially reviewed): on a TRUE cold launch — and ONLY when the
 * per-account feature flag is on (David first; the client path is byte-identical
 * until validated) — AttoVoipBootstrap decodes the push ITSELF via
 * `[TwilioVoiceSDK handleNotification:delegate:self ...]` (synchronous per the
 * framework header) and reports on its OWN launch-owned `CXProvider` using the
 * real `callInvite.uuid`, then calls `completion()`. It also owns answer+audio
 * for that cold call (accept the invite, wire the TwilioVoice.DefaultAudioDevice) so the
 * call connects with two-way audio from the lock screen. The warm/foreground/
 * warm-background path is DECIDED by a race-free "module alive" signal (the
 * patched module posts `AttoTwilioModuleDidInit` on -init) and is left BYTE-
 * IDENTICAL: it still runs the proven `deliverIncomingPush` re-post loop.
 *
 * NOT covered by this iteration (needs the RN-module handoff surgery + on-device
 * validation): in-app mid-call controls (mute / in-app hangup / DTMF keypad) for
 * a call ANSWERED on cold launch — those go through the module's callMap which
 * this iteration doesn't populate. Hang-up from the CallKit UI works. That's why
 * the whole cold path is flag-gated to David until validated.
 *
 * ── Original device-token rationale (unchanged) ──
 * `@twilio/voice-react-native-sdk`'s native module learns its PushKit device
 * token by observing an `NSNotification` a `PKPushRegistry` delegate posts. In
 * the stock SDK that delegate is created by `voice.initializePushRegistry()`
 * from JS — too late for a cold launch. So we keep a SINGLE registry owned by
 * this bootstrap, cache the token the moment iOS delivers it, and RE-EMIT the
 * SDK's notification until the module (which subscribes lazily on first JS use)
 * observes it. JS must NOT call `voice.initializePushRegistry()` — see
 * `front/src/hooks/useTwilioVoice.ts`.
 *
 * This project uses CNG (`ios/` is git-ignored and regenerated by prebuild/EAS),
 * so the AppDelegate is patched via this plugin. The helper class is appended to
 * `AppDelegate.swift` itself. The Twilio-module-side pieces (module-alive marker,
 * audio-device guard) ship as a patch-package edit to the SDK.
 */

const IMPORT_ANCHOR = 'import ReactAppDependencyProvider\n';
const IMPORT_INJECT =
  'import ReactAppDependencyProvider\nimport PushKit\nimport UIKit\nimport CallKit\nimport AVFoundation\nimport TwilioVoice\n';

const PROPERTY_ANCHOR = 'var reactNativeFactory: RCTReactNativeFactory?\n';
const PROPERTY_INJECT =
  'var reactNativeFactory: RCTReactNativeFactory?\n\n  var attoVoipBootstrap: AttoVoipBootstrap?\n';

const INIT_BLOCK = [
  "    // Bring up the VoIP PushKit registry before anything else so the push",
  '    // delegate is alive from launch: it caches the device token (re-emitting',
  "    // it to Twilio's RN module once that module subscribes), forwards incoming",
  '    // pushes, and — on a flag-gated cold launch — reports to CallKit itself so',
  '    // iOS never terminates the app. See withTwilioVoipPushRegistry.',
  '    let bootstrap = AttoVoipBootstrap()',
  '    bootstrap.start()',
  '    attoVoipBootstrap = bootstrap',
  '',
].join('\n');

/**
 * iOS memory-warning override, appended to the AppDelegate class.
 *
 * Fires BEFORE jetsam terminates the app, and on a system callback that keeps
 * running even when the JS thread is stalled — so it is the earliest available
 * signal on the out-of-memory path that was silently killing calls mid-call
 * (no crash report is generated for a jetsam kill). JS surfaces it as
 * `call_memory_warning`.
 */
const MEMORY_WARNING_OVERRIDE = [
  '  public override func applicationDidReceiveMemoryWarning(_ application: UIApplication) {',
  '    let now = Date().timeIntervalSince1970',
  '    UserDefaults.standard.set(now, forKey: "atto_last_mem_warning_at")',
  '    let prior = UserDefaults.standard.integer(forKey: "atto_mem_warning_count")',
  '    UserDefaults.standard.set(prior + 1, forKey: "atto_mem_warning_count")',
  '    NSLog("[AttoMem] didReceiveMemoryWarning at=\\(now) count=\\(prior + 1)")',
  '    super.applicationDidReceiveMemoryWarning(application)',
  '  }',
  '',
].join('\n');

const BOOTSTRAP_CLASS = `

/// Single, launch-owned VoIP \`PKPushRegistry\` for the Twilio Voice RN SDK, plus
/// a launch-owned CallKit \`CXProvider\` used ONLY on a flag-gated cold launch to
/// satisfy PushKit's report-before-completion contract when the RN module isn't
/// alive yet. See withTwilioVoipPushRegistry.js for the full rationale.
final class AttoVoipBootstrap: NSObject, PKPushRegistryDelegate, CXCallObserverDelegate, TwilioVoice.NotificationDelegate, CXProviderDelegate, TwilioVoice.CallDelegate {
  // These string constants must match @twilio/voice-react-native-sdk's
  // TwilioVoicePushRegistry.m exactly — the SDK module observes this exact
  // notification name / keys to learn its device token and incoming pushes.
  private static let notificationName = Notification.Name("TwilioVoicePushRegistryNotification")
  private static let eventTypeKey = "type"
  private static let deviceTokenUpdated = "deviceTokenUpdated"
  private static let deviceTokenKey = "deviceToken"
  private static let incomingPushReceived = "incomingPushReceived"
  private static let incomingPushPayloadKey = "incomingPushPayload"

  // Cold-launch feature flag (per-account, set by JS via NSUserDefaults). When
  // OFF, the incoming-push path is byte-identical to the historical behaviour —
  // the client is never exposed to the new native-report branch until validated.
  private static let coldFlagKey = "atto_coldlaunch_callkit_enabled"
  // Written by this bootstrap while a bootstrap-owned cold call is live; read by
  // the patched Twilio module's -init so it does NOT swap the audio device
  // mid-call (the SDK forbids that). Cleared on disconnect.
  private static let coldCallLiveKey = "atto_cold_call_live"

  private var voipRegistry: PKPushRegistry?
  private var cachedToken: Data?
  private var reemitTimer: Timer?
  private var reemitCount = 0
  private let callObserver = CXCallObserver()

  // Race-free "is the Twilio RN module alive this process" signal: the patched
  // module posts AttoTwilioModuleDidInit inside -init; we flip this true. On a
  // cold launch the incoming push arrives BEFORE that, so this stays false and we
  // take the native-report branch. Once true, the module is the sole reporter.
  private var moduleAlive = false

  // Cold-launch CallKit state (bootstrap-owned).
  private var coldProvider: CXProvider?
  private var heldInvites: [String: TwilioVoice.CallInvite] = [:]
  private var heldCalls: [String: TwilioVoice.Call] = [:]
  private var coldAudioDevice: TwilioVoice.DefaultAudioDevice?
  private var pendingPushCompletion: (() -> Void)?
  private var reportedThisPush = false

  private var coldEnabled: Bool { UserDefaults.standard.bool(forKey: AttoVoipBootstrap.coldFlagKey) }

  func start() {
    let registry = PKPushRegistry(queue: .main)
    registry.delegate = self
    registry.desiredPushTypes = [.voIP]
    voipRegistry = registry

    callObserver.setDelegate(self, queue: .main)

    // Launch-owned CallKit provider (config matches the SDK's so cold-launch call
    // UI is consistent with warm calls). Only used on the cold-launch branch.
    let config = CXProviderConfiguration()
    config.maximumCallGroups = 1
    config.maximumCallsPerCallGroup = 1
    config.supportsVideo = false
    config.supportedHandleTypes = [.generic, .phoneNumber]
    let provider = CXProvider(configuration: config)
    provider.setDelegate(self, queue: nil)
    coldProvider = provider

    // The module subscribes lazily (~3s after first JS use) and iOS never replays
    // the early device-token notification — so re-emit the cached token on
    // becoming active and on a short timer until the module catches it.
    NotificationCenter.default.addObserver(
      self, selector: #selector(reemitToken),
      name: UIApplication.didBecomeActiveNotification, object: nil)
    // Race-free module-alive signal (posted by the patched Twilio module -init).
    NotificationCenter.default.addObserver(
      self, selector: #selector(moduleDidInit),
      name: Notification.Name("AttoTwilioModuleDidInit"), object: nil)
    reemitTimer = Timer.scheduledTimer(
      timeInterval: 1.0, target: self, selector: #selector(reemitTick),
      userInfo: nil, repeats: true)
  }

  @objc private func moduleDidInit() {
    moduleAlive = true
    NSLog("[AttoVoip] Twilio RN module alive")
  }

  @objc private func reemitTick() {
    reemitCount += 1
    reemitToken()
    if reemitCount == 25 {
      reemitTimer?.invalidate()
      reemitTimer = Timer.scheduledTimer(
        timeInterval: 5.0, target: self, selector: #selector(reemitTick),
        userInfo: nil, repeats: true)
    }
  }

  @objc private func reemitToken() {
    guard let token = cachedToken else { return }
    postToken(token)
  }

  private func postToken(_ token: Data) {
    NotificationCenter.default.post(
      name: AttoVoipBootstrap.notificationName, object: nil,
      userInfo: [
        AttoVoipBootstrap.eventTypeKey: AttoVoipBootstrap.deviceTokenUpdated,
        AttoVoipBootstrap.deviceTokenKey: token,
      ])
  }

  // Native cold-launch telemetry: stamp a marker + timestamp into UserDefaults so
  // the next foreground can ship it to PostHog (and it shows in Console via NSLog).
  private func mark(_ event: String) {
    let ud = UserDefaults.standard
    ud.set(Date().timeIntervalSince1970, forKey: "atto_coldcallkit_\\(event)_at")
    NSLog("[AttoColdCallKit] \\(event)")
  }

  // MARK: - PKPushRegistryDelegate

  func pushRegistry(_ registry: PKPushRegistry, didUpdate pushCredentials: PKPushCredentials, for type: PKPushType) {
    guard type == .voIP else { return }
    cachedToken = pushCredentials.token
    NSLog("[AttoVoip] device token received (\\(pushCredentials.token.count) bytes), emitting to RN module")
    postToken(pushCredentials.token)
  }

  func pushRegistry(
    _ registry: PKPushRegistry,
    didReceiveIncomingPushWith payload: PKPushPayload,
    for type: PKPushType,
    completion: @escaping () -> Void
  ) {
    guard type == .voIP else { completion(); return }

    let state = UIApplication.shared.applicationState.rawValue
    let now = Date().timeIntervalSince1970
    UserDefaults.standard.set(now, forKey: "atto_last_voip_push_at")
    UserDefaults.standard.set(state, forKey: "atto_last_voip_push_appstate")
    NSLog("[AttoVoip] VoIP push received appState=\\(state) moduleAlive=\\(moduleAlive) coldEnabled=\\(coldEnabled) at=\\(now)")

    // WARM / foreground / warm-background (module alive) OR feature OFF → the
    // proven, byte-identical path: post the notification (an alive module reports
    // synchronously) and re-post idempotently until CallKit shows the call.
    if !coldEnabled || moduleAlive {
      deliverIncomingPush(payload.dictionaryPayload, attempt: 0, completion: completion)
      return
    }

    // TRUE COLD LAUNCH + feature ON: the module can't report in time. Decode the
    // push ourselves (synchronous per the TwilioVoice header) and report on our
    // own provider inside the push window. We CONSUME the push (do not post to the
    // module) so it never double-decodes/double-reports.
    mark("cold_push")
    pendingPushCompletion = completion
    reportedThisPush = false
    let recognized = TwilioVoiceSDK.handleNotification(
      payload: payload.dictionaryPayload, delegate: self, delegateQueue: nil, callMessageDelegate: nil)
    // handleNotification is synchronous: callInviteReceived/cancelled already ran.
    if !reportedThisPush {
      // No invite reported (cancel, non-Twilio, or decode failure). We STILL must
      // report+complete or iOS kills us. Report a short-lived placeholder.
      NSLog("[AttoColdCallKit] no invite reported (recognized=\\(recognized)) — placeholder + complete")
      reportPlaceholderAndComplete()
    }
  }

  private func releasePendingCompletion() {
    if let c = pendingPushCompletion {
      pendingPushCompletion = nil
      c()
    }
  }

  private func reportPlaceholderAndComplete() {
    let uuid = UUID()
    let update = CXCallUpdate()
    update.remoteHandle = CXHandle(type: .generic, value: "Incoming call")
    update.hasVideo = false
    coldProvider?.reportNewIncomingCall(with: uuid, update: update) { [weak self] _ in
      // End the phantom shortly so it can't linger if the push was spurious.
      DispatchQueue.main.asyncAfter(deadline: .now() + 6.0) {
        self?.coldProvider?.reportCall(with: uuid, endedAt: nil, reason: .remoteEnded)
      }
    }
    releasePendingCompletion()
  }

  // MARK: - TwilioVoice.NotificationDelegate (cold-launch decode)

  func callInviteReceived(callInvite: TwilioVoice.CallInvite) {
    heldInvites[callInvite.uuid.uuidString] = callInvite
    let update = buildUpdate(for: callInvite)
    // Report on OUR provider with the SDK's real invite UUID (same UUID we later
    // accept with → CallKit shows exactly one call, answerable natively).
    coldProvider?.reportNewIncomingCall(with: callInvite.uuid, update: update) { error in
      if let error = error { NSLog("[AttoColdCallKit] report failed: \\(error)") }
    }
    reportedThisPush = true
    mark("cold_report")
    releasePendingCompletion()
  }

  func cancelledCallInviteReceived(cancelledCallInvite: TwilioVoice.CancelledCallInvite, error: Error) {
    mark("cold_cancelled")
    // End the matching CallKit call (match by callSid — cancel has no uuid).
    for (uuidString, invite) in heldInvites where invite.callSid == cancelledCallInvite.callSid {
      if let uuid = UUID(uuidString: uuidString) {
        coldProvider?.reportCall(with: uuid, endedAt: nil, reason: .remoteEnded)
      }
      heldInvites.removeValue(forKey: uuidString)
    }
    UserDefaults.standard.set(false, forKey: AttoVoipBootstrap.coldCallLiveKey)
    // A cancel push must still complete the PushKit handler.
    releasePendingCompletion()
  }

  private func buildUpdate(for callInvite: TwilioVoice.CallInvite) -> CXCallUpdate {
    var handleName = callInvite.from ?? "Unknown Caller"
    // Reproduce the SDK's @username handle: NSUserDefaults template +
    // customParameters substitution (getDisplayName in +CallKit.m).
    if let template = UserDefaults.standard.string(forKey: "incomingCallContactHandleTemplate"),
       !template.isEmpty {
      var processed = template
      for (key, value) in (callInvite.customParameters ?? [:]) {
        processed = processed.replacingOccurrences(of: "\${" + key + "}", with: value)
      }
      handleName = processed
    }
    let update = CXCallUpdate()
    update.remoteHandle = CXHandle(type: .generic, value: handleName)
    update.localizedCallerName = handleName
    update.supportsDTMF = true
    update.supportsHolding = true
    update.supportsGrouping = false
    update.supportsUngrouping = false
    update.hasVideo = false
    return update
  }

  private func callKitHasLiveCall() -> Bool {
    return callObserver.calls.contains { !$0.hasEnded }
  }

  // MARK: - Warm / feature-off path (unchanged, proven)

  // Report-window ceiling. Was 10 (~5s), which KILLED THE APP on cold launch: a
  // VoIP push to a terminated app must launch RN, boot JS and init the Twilio
  // module before anything can report to CallKit, and that regularly took longer
  // than 5s. completion() then fired with no call reported, so iOS terminated us
  // ("never posted an incoming call after a PushKit VoIP push", Sentry
  // NSInternalInconsistencyException x9 on b115) and throttled future VoIP
  // delivery — the client's "Larry is calling but it's not coming through".
  // 24 x 0.5s ~= 12s gives the cold-boot path room while staying inside iOS's
  // VoIP background window. atto_last_voip_report_* records the outcome.
  private static let maxDeliverAttempts = 24

  private func recordReportOutcome(_ outcome: String, attempt: Int) {
    UserDefaults.standard.set(outcome, forKey: "atto_last_voip_report_outcome")
    UserDefaults.standard.set(attempt, forKey: "atto_last_voip_report_attempt")
    UserDefaults.standard.set(Date().timeIntervalSince1970, forKey: "atto_last_voip_report_at")
  }

  private func deliverIncomingPush(_ payload: [AnyHashable: Any], attempt: Int, completion: @escaping () -> Void) {
    if callKitHasLiveCall() {
      recordReportOutcome("reported", attempt: attempt)
      completion()
      return
    }

    NotificationCenter.default.post(
      name: AttoVoipBootstrap.notificationName, object: nil,
      userInfo: [
        AttoVoipBootstrap.eventTypeKey: AttoVoipBootstrap.incomingPushReceived,
        AttoVoipBootstrap.incomingPushPayloadKey: payload,
      ])

    if callKitHasLiveCall() {
      recordReportOutcome("reported", attempt: attempt)
      completion()
      return
    }

    if attempt >= AttoVoipBootstrap.maxDeliverAttempts {
      NSLog("[AttoVoip] VoIP push: CallKit never reported after \\(attempt) re-posts; releasing")
      recordReportOutcome("gave_up", attempt: attempt)
      completion()
      return
    }

    DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) { [weak self] in
      self?.deliverIncomingPush(payload, attempt: attempt + 1, completion: completion)
    }
  }

  // MARK: - CXProviderDelegate (cold-launch answer/end/audio)

  func providerDidReset(_ provider: CXProvider) {
    coldAudioDevice?.isEnabled = false
  }

  func provider(_ provider: CXProvider, didActivate audioSession: AVAudioSession) {
    // Enabling the TwilioVoice.DefaultAudioDevice is the ONLY thing that starts RTP.
    coldAudioDevice?.isEnabled = true
    mark("cold_didActivate")
  }

  func provider(_ provider: CXProvider, didDeactivate audioSession: AVAudioSession) {
    coldAudioDevice?.isEnabled = false
    mark("cold_didDeactivate")
  }

  func provider(_ provider: CXProvider, perform action: CXAnswerCallAction) {
    mark("cold_answerAction")
    guard let invite = heldInvites[action.callUUID.uuidString] else {
      action.fail(); return
    }
    // The RN module hasn't run -init, so no TVOAudioDevice is registered with the
    // SDK yet. Register a default one BEFORE accepting so the call has RTP (use the
    // same factory the SDK uses). The patched module -init will adopt this device
    // instead of swapping it mid-call.
    let device = TwilioVoice.DefaultAudioDevice()
    coldAudioDevice = device
    TwilioVoiceSDK.audioDevice = device
    UserDefaults.standard.set(true, forKey: AttoVoipBootstrap.coldCallLiveKey)

    let options = TwilioVoice.AcceptOptions(callInvite: invite) { builder in
      builder.uuid = invite.uuid
    }
    let call = invite.accept(options: options, delegate: self)
    heldCalls[action.callUUID.uuidString] = call
    action.fulfill()
  }

  func provider(_ provider: CXProvider, perform action: CXEndCallAction) {
    if let call = heldCalls[action.callUUID.uuidString] {
      call.disconnect()
    } else if let invite = heldInvites[action.callUUID.uuidString] {
      invite.reject()
      heldInvites.removeValue(forKey: action.callUUID.uuidString)
    }
    UserDefaults.standard.set(false, forKey: AttoVoipBootstrap.coldCallLiveKey)
    action.fulfill()
  }

  func provider(_ provider: CXProvider, perform action: CXSetMutedCallAction) {
    if let call = heldCalls[action.callUUID.uuidString] {
      call.isMuted = action.isMuted
      action.fulfill()
    } else { action.fail() }
  }

  func provider(_ provider: CXProvider, perform action: CXSetHeldCallAction) {
    if let call = heldCalls[action.callUUID.uuidString] {
      call.isOnHold = action.isOnHold
      action.fulfill()
    } else { action.fail() }
  }

  func provider(_ provider: CXProvider, perform action: CXPlayDTMFCallAction) {
    if let call = heldCalls[action.callUUID.uuidString] {
      call.sendDigits(action.digits)
      action.fulfill()
    } else { action.fail() }
  }

  // MARK: - TwilioVoice.CallDelegate (cold call lifecycle)

  func callDidConnect(call: TwilioVoice.Call) {
    mark("cold_connected")
  }

  func callDidDisconnect(call: TwilioVoice.Call, error: Error?) {
    finishColdCall(call)
  }

  func callDidFailToConnect(call: TwilioVoice.Call, error: Error) {
    NSLog("[AttoColdCallKit] cold call failed to connect: \\(error)")
    finishColdCall(call)
  }

  private func finishColdCall(_ call: TwilioVoice.Call) {
    mark("cold_disconnected")
    coldProvider?.reportCall(with: call.uuid ?? UUID(), endedAt: nil, reason: .remoteEnded)
    if let uuid = call.uuid?.uuidString { heldCalls.removeValue(forKey: uuid) }
    coldAudioDevice?.isEnabled = false
    UserDefaults.standard.set(false, forKey: AttoVoipBootstrap.coldCallLiveKey)
  }

  // CXCallObserverDelegate — we only read callObserver.calls synchronously.
  func callObserver(_ callObserver: CXCallObserver, callChanged call: CXCall) {}

  func pushRegistry(_ registry: PKPushRegistry, didInvalidatePushTokenFor type: PKPushType) {
    if type == .voIP { cachedToken = nil }
  }
}
`;

module.exports = function withTwilioVoipPushRegistry(config) {
  return withAppDelegate(config, (cfg) => {
    if (cfg.modResults.language !== 'swift') {
      throw new Error(
        `[withTwilioVoipPushRegistry] Expected a Swift AppDelegate, got "${cfg.modResults.language}".`
      );
    }

    let src = cfg.modResults.contents;
    if (src.includes('AttoVoipBootstrap')) return cfg; // already patched

    // 1) PushKit / UIKit / CallKit / TwilioVoice imports.
    if (!src.includes('import PushKit')) {
      if (!src.includes(IMPORT_ANCHOR)) {
        throw new Error(
          '[withTwilioVoipPushRegistry] Could not find the import anchor — AppDelegate template changed.'
        );
      }
      src = src.replace(IMPORT_ANCHOR, IMPORT_INJECT);
    }

    // 2) Retained property so the registry delegate is not deallocated.
    if (!src.includes(PROPERTY_ANCHOR)) {
      throw new Error(
        '[withTwilioVoipPushRegistry] Could not find the reactNativeFactory property anchor — AppDelegate template changed.'
      );
    }
    src = src.replace(PROPERTY_ANCHOR, PROPERTY_INJECT);

    // 3) Create + start the bootstrap first thing in didFinishLaunching.
    const afterInit = src.replace(
      /(didFinishLaunchingWithOptions[^\n]*\n\s*\) -> Bool \{\n)/,
      `$1${INIT_BLOCK}`
    );
    if (afterInit === src) {
      throw new Error(
        '[withTwilioVoipPushRegistry] Could not find didFinishLaunchingWithOptions to inject the bootstrap — AppDelegate template changed.'
      );
    }
    src = afterInit;

    // 3b) iOS memory-warning hook. Fires BEFORE jetsam terminates the app and
    // runs on a system callback that survives a frozen JS thread, so it is the
    // earliest signal on the OOM path that silently killed calls. Stamped to
    // NSUserDefaults; JS reports it as `call_memory_warning`. Injected only if
    // the AppDelegate doesn't already override it.
    if (!src.includes('applicationDidReceiveMemoryWarning')) {
      const afterMem = src.replace(
        /(\n\s*\/\/ Linking API\n)/,
        `\n${MEMORY_WARNING_OVERRIDE}$1`
      );
      if (afterMem === src) {
        // Fall back to injecting before the final closing brace of the class.
        const lastBrace = src.lastIndexOf('\n}');
        if (lastBrace !== -1) {
          src = `${src.slice(0, lastBrace)}\n${MEMORY_WARNING_OVERRIDE}${src.slice(lastBrace)}`;
        }
      } else {
        src = afterMem;
      }
    }

    // 4) Append the native helper class to the same file.
    src = `${src.trimEnd()}\n${BOOTSTRAP_CLASS}`;

    cfg.modResults.contents = src;
    return cfg;
  });
};
