const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Xcode 26.x's clang rejects fmt 11's consteval format strings whenever the
 * `fmt` pod is compiled from scratch (Sep 23 2026, local preview build):
 *
 *   call to consteval function 'fmt::basic_format_string<...>' is not a
 *   constant expression   (Pods/fmt/include/fmt/format-inl.h)
 *
 * Earlier builds only passed because DerivedData still held fmt objects
 * compiled by an older toolchain. Defining FMT_CONSTEVAL empty does NOT work:
 * base.h decides FMT_USE_CONSTEVAL from the language level and redefines the
 * macro. Compiling the fmt pod as C++17 makes that decision 0 for the one
 * translation unit that fails (format.cc). The Podfile is regenerated by
 * prebuild, so the setting is injected here rather than edited in ios/Podfile.
 */
const MARKER = '# withFmtConsteval';
const INJECT = `
    ${MARKER}: Xcode 26 rejects fmt 11's consteval strings, see plugins/withFmtConsteval.js.
    # Runs AFTER react_native_post_install so nothing rewrites the setting.
    # fmt hard codes FMT_USE_CONSTEVAL from the language level, so a -D
    # cannot switch it off; compiling the fmt pod itself as C++17 can, and
    # its exported functions do not change shape between the two standards.
    installer.pods_project.targets.each do |target|
      next unless target.name == 'fmt'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
      end
    end
`;

module.exports = function withFmtConsteval(config) {
  return withDangerousMod(config, [
    'ios',
    (cfg) => {
      const podfile = path.join(cfg.modRequest.platformProjectRoot, 'Podfile');
      let src = fs.readFileSync(podfile, 'utf8');
      if (src.includes(MARKER)) return cfg;
      // Inject at the END of the post_install block: after the closing paren
      // of react_native_post_install(...) and before the block's `end`.
      const re = /(post_install do \|installer\|\n[\s\S]*?react_native_post_install\([\s\S]*?\n\s*\)\n)/;
      if (!re.test(src)) {
        throw new Error('[withFmtConsteval] react_native_post_install call not found in the Podfile');
      }
      src = src.replace(re, `$1${INJECT}`);
      fs.writeFileSync(podfile, src);
      return cfg;
    },
  ]);
};
