const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Xcode 26.x's clang rejects fmt 11's consteval format strings whenever the
 * `fmt` pod is compiled from scratch (Sep 23 2026, local preview build):
 *
 *   call to consteval function 'fmt::basic_format_string<...>' is not a
 *   constant expression   (Pods/fmt/include/fmt/format-inl.h)
 *
 * Earlier builds only passed because DerivedData still held fmt objects
 * compiled by an older toolchain. Defining FMT_CONSTEVAL empty is the
 * upstream workaround: fmt compiles its format strings as plain constexpr
 * and nothing changes at runtime. The Podfile is regenerated by prebuild, so
 * the setting has to be injected here, inside react_native_post_install's
 * block, rather than edited in ios/Podfile.
 */
const MARKER = '# withFmtConsteval';
const INJECT = `
    ${MARKER}: Xcode 26 rejects fmt 11's consteval strings, see plugins/withFmtConsteval.js.
    # Runs AFTER react_native_post_install so nothing rewrites these settings,
    # and on EVERY pod target: fmt's headers are included by folly and React
    # core too, and a preprocessor definition is what the compiler honours.
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        defs = Array(config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] || ['$(inherited)'])
        defs << 'FMT_CONSTEVAL=' unless defs.include?('FMT_CONSTEVAL=')
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = defs
        flags = Array(config.build_settings['OTHER_CPLUSPLUSFLAGS'] || ['$(inherited)'])
        flags << '-DFMT_CONSTEVAL=' unless flags.include?('-DFMT_CONSTEVAL=')
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] = flags
      end
    end
`;

module.exports = function withFmtConsteval(config) {
  return withDangerousMod(config, [
    'ios',
    (cfg) => {
      const podfile = path.join(cfg.modRequest.platformProjectRoot, 'Podfile');
      let src = fs.readFileSync(podfile, 'utf8');
      if (src.includes(MARKER)) return cfg;
      // Inject at the END of the post_install block: after the closing paren
      // of react_native_post_install(...) and before the block's `end`.
      const re = /(post_install do \|installer\|\n[\s\S]*?react_native_post_install\([\s\S]*?\n\s*\)\n)/;
      if (!re.test(src)) {
        throw new Error('[withFmtConsteval] react_native_post_install call not found in the Podfile');
      }
      src = src.replace(re, `$1${INJECT}`);
      fs.writeFileSync(podfile, src);
      return cfg;
    },
  ]);
};
