const { withAppDelegate } = require('@expo/config-plugins');

/**
 * withTwilioVoipPushRegistry
 * --------------------------
 * Owns the app's single VoIP `PKPushRegistry` natively, from process launch,
 * so an incoming call survives a cold launch from a terminated state AND the
 * Twilio React-Native SDK still receives its device token reliably.
 *
 * The device-token half (cache + re-emit) is unchanged and load-bearing — see
 * the long history below. The INCOMING-PUSH half now has a cold-launch path.
 *
 * ── Cold-launch CallKit crash (Jul 2026, build 72, client) ──────────────────
 * iOS's PushKit contract: after `didReceiveIncomingPushWith` you MUST call
 * `CXProvider.reportNewIncomingCall` BEFORE `completion()` returns, in the same
 * run loop, or iOS TERMINATES the app (`_terminateAppIfThereAreUnhandledVoIPPushes`
 * → NSInternalInconsistencyException) AND, on repeat offenses, stops delivering
 * VoIP pushes entirely. The Twilio RN module is the sole reporter, but it is a
 * lazily-instantiated TurboModule whose CXProvider is built in `-init` (~3s after
 * the JS bridge boots). On a fully-killed cold launch the module does not exist,
 * so the old "post the notification and re-post every 0.5s" loop NEVER got a
 * report and eventually called `completion()` bare → the crash (confirmed dual
 * source: Sentry + PostHog, see project_twilio_coldlaunch_callkit).
 *
 * The fix (adversarially reviewed): on a TRUE cold launch — and ONLY when the
 * per-account feature flag is on (David first; the client path is byte-identical
 * until validated) — AttoVoipBootstrap decodes the push ITSELF via
 * `[TwilioVoiceSDK handleNotification:delegate:self ...]` (synchronous per the
 * framework header) and reports on its OWN launch-owned `CXProvider` using the
 * real `callInvite.uuid`, then calls `completion()`. It also owns answer+audio
 * for that cold call (accept the invite, wire the TwilioVoice.DefaultAudioDevice) so the
 * call connects with two-way audio from the lock screen. The warm/foreground/
 * warm-background path is DECIDED by a race-free "module alive" signal (the
 * patched module posts `AttoTwilioModuleDidInit` on -init) and is left BYTE-
 * IDENTICAL: it still runs the proven `deliverIncomingPush` re-post loop.
 *
 * NOT covered by this iteration (needs the RN-module handoff surgery + on-device
 * validation): in-app mid-call controls (mute / in-app hangup / DTMF keypad) for
 * a call ANSWERED on cold launch — those go through the module's callMap which
 * this iteration doesn't populate. Hang-up from the CallKit UI works. That's why
 * the whole cold path is flag-gated to David until validated.
 *
 * ── Original device-token rationale (unchanged) ──
 * `@twilio/voice-react-native-sdk`'s native module learns its PushKit device
 * token by observing an `NSNotification` a `PKPushRegistry` delegate posts. In
 * the stock SDK that delegate is created by `voice.initializePushRegistry()`
 * from JS — too late for a cold launch. So we keep a SINGLE registry owned by
 * this bootstrap, cache the token the moment iOS delivers it, and RE-EMIT the
 * SDK's notification until the module (which subscribes lazily on first JS use)
 * observes it. JS must NOT call `voice.initializePushRegistry()` — see
 * `front/src/hooks/useTwilioVoice.ts`.
 *
 * This project uses CNG (`ios/` is git-ignored and regenerated by prebuild/EAS),
 * so the AppDelegate is patched via this plugin. The helper class is appended to
 * `AppDelegate.swift` itself. The Twilio-module-side pieces (module-alive marker,
 * audio-device guard) ship as a patch-package edit to the SDK.
 */

const IMPORT_ANCHOR = 'import ReactAppDependencyProvider\n';
const IMPORT_INJECT =
  'import ReactAppDependencyProvider\nimport PushKit\nimport UIKit\nimport CallKit\nimport AVFoundation\nimport MetricKit\nimport TwilioVoice\n#if canImport(Sentry)\nimport Sentry\n#endif\n';

const PROPERTY_ANCHOR = 'var reactNativeFactory: RCTReactNativeFactory?\n';
const PROPERTY_INJECT =
  'var reactNativeFactory: RCTReactNativeFactory?\n\n  var attoVoipBootstrap: AttoVoipBootstrap?\n';

const INIT_BLOCK = [
  '    // Bring up the VoIP PushKit registry before anything else so the push',
  '    // delegate is alive from launch: it caches the device token (re-emitting',
  "    // it to Twilio's RN module once that module subscribes), forwards incoming",
  '    // pushes, and — on a flag-gated cold launch — reports to CallKit itself so',
  '    // iOS never terminates the app. See withTwilioVoipPushRegistry.',
  '    let bootstrap = AttoVoipBootstrap()',
  '    bootstrap.start()',
  '    attoVoipBootstrap = bootstrap',
  '',
].join('\n');

/**
 * iOS memory-warning override, appended to the AppDelegate class.
 *
 * Fires BEFORE jetsam terminates the app, and on a system callback that keeps
 * running even when the JS thread is stalled — so it is the earliest available
 * signal on the out-of-memory path that was silently killing calls mid-call
 * (no crash report is generated for a jetsam kill). JS surfaces it as
 * `call_memory_warning`.
 */
const MEMORY_WARNING_OVERRIDE = [
  '  public override func applicationDidReceiveMemoryWarning(_ application: UIApplication) {',
  '    let now = Date().timeIntervalSince1970',
  '    UserDefaults.standard.set(now, forKey: "atto_last_mem_warning_at")',
  '    let prior = UserDefaults.standard.integer(forKey: "atto_mem_warning_count")',
  '    UserDefaults.standard.set(prior + 1, forKey: "atto_mem_warning_count")',
  '    NSLog("[AttoMem] didReceiveMemoryWarning at=\\(now) count=\\(prior + 1)")',
  '    super.applicationDidReceiveMemoryWarning(application)',
  '  }',
  '',
].join('\n');

const BOOTSTRAP_CLASS = `

/// Single, launch-owned VoIP \`PKPushRegistry\` for the Twilio Voice RN SDK, plus
/// a launch-owned CallKit \`CXProvider\` used ONLY on a flag-gated cold launch to
/// satisfy PushKit's report-before-completion contract when the RN module isn't
/// alive yet. See withTwilioVoipPushRegistry.js for the full rationale.
final class AttoVoipBootstrap: NSObject, PKPushRegistryDelegate, CXCallObserverDelegate, TwilioVoice.NotificationDelegate, CXProviderDelegate, TwilioVoice.CallDelegate {
  // These string constants must match @twilio/voice-react-native-sdk's
  // TwilioVoicePushRegistry.m exactly — the SDK module observes this exact
  // notification name / keys to learn its device token and incoming pushes.
  private static let notificationName = Notification.Name("TwilioVoicePushRegistryNotification")
  private static let eventTypeKey = "type"
  private static let deviceTokenUpdated = "deviceTokenUpdated"
  private static let deviceTokenKey = "deviceToken"
  private static let incomingPushReceived = "incomingPushReceived"
  private static let incomingPushPayloadKey = "incomingPushPayload"

  // Cold-launch protection is now ALWAYS ON by default (Aug 13). It was gated
  // behind an OPT-IN flag that sat off for a month, so every cold-launch VoIP
  // push crashed the app (iOS "never posted an incoming call"), and the fix
  // could not even self-activate: the flag was read from disk, but disk is only
  // written on a successful launch — the exact thing a crash-loop prevents. A
  // fatal-crash guard must never depend on a prior launch or a remote flag. So
  // the safe native-report branch is the DEFAULT, and this key is only an
  // emergency OPT-OUT (default false ⇒ protection on) for the rare case the
  // native path itself ever misbehaves on some device.
  private static let coldKillKey = "atto_coldlaunch_callkit_disabled"
  // Written by this bootstrap while a bootstrap-owned cold call is live; read by
  // the patched Twilio module's -init so it does NOT swap the audio device
  // mid-call (the SDK forbids that). Cleared on disconnect.
  private static let coldCallLiveKey = "atto_cold_call_live"

  private var voipRegistry: PKPushRegistry?
  private var cachedToken: Data?
  private var reemitTimer: Timer?
  private var reemitCount = 0
  private let callObserver = CXCallObserver()

  // Race-free "is the Twilio RN module alive this process" signal: the patched
  // module posts AttoTwilioModuleDidInit inside -init; we flip this true. On a
  // cold launch the incoming push arrives BEFORE that, so this stays false and we
  // take the native-report branch. Once true, the module is the sole reporter.
  private var moduleAlive = false

  // Cold-launch CallKit state (bootstrap-owned).
  private var coldProvider: CXProvider?
  private var heldInvites: [String: TwilioVoice.CallInvite] = [:]
  private var heldCalls: [String: TwilioVoice.Call] = [:]
  // Per-call connect time, handed to the RN module at adoption so JS shows the
  // real call duration (feeds the module's callConnectMap / initialConnectedTimestamp).
  private var heldCallConnectedAt: [String: Date] = [:]
  // Protocol type (not DefaultAudioDevice) so it can ALSO hold the audio-INJECTION
  // engine's custom TVOAudioDevice when injection is on — see the accept handler.
  private var coldAudioDevice: TwilioVoice.AudioDevice?
  private var pendingPushCompletion: (() -> Void)?
  private var reportedThisPush = false
  // Guards so a VoIP push is completed EXACTLY once and NEVER left unhandled: an
  // unhandled push is redelivered by iOS on the next launch and can jam the app
  // on the splash (the Aug 13 "won't open"). completePush() is idempotent; a hard
  // deadline forces it if every other path failed to.
  private var pushCompleted = false
  private var hardDeadlineWork: DispatchWorkItem?
  // The UUID we reported to CallKit for THIS push (a placeholder reported
  // immediately, then updated in place when the invite decodes). Accept + cancel
  // reference this so CallKit only ever sees ONE call per push.
  private var coldReportUUID: UUID?
  private var inviteDecodedThisPush = false

  // OPT-OUT: protection is on unless something explicitly disabled it. An unset
  // key reads false ⇒ enabled, so a fresh install with no launch is still safe.
  private var coldDisabled: Bool { UserDefaults.standard.bool(forKey: AttoVoipBootstrap.coldKillKey) }

  func start() {
    let registry = PKPushRegistry(queue: .main)
    registry.delegate = self
    registry.desiredPushTypes = [.voIP]
    voipRegistry = registry

    callObserver.setDelegate(self, queue: .main)

    // Launch-owned CallKit provider (config matches the SDK's so cold-launch call
    // UI is consistent with warm calls). Only used on the cold-launch branch.
    let config = CXProviderConfiguration()
    config.maximumCallGroups = 1
    config.maximumCallsPerCallGroup = 1
    // VIDEO-CALL trick, ported from the warm path's b97 module patch (b150): an
    // audio-only CallKit call CANNOT self-foreground the app after a locked
    // answer — marking the call as video (supportsVideo here + hasVideo on every
    // CXCallUpdate) is the Apple-DTS-sanctioned way to make iOS launch ATTO into
    // the foreground on unlock, which is what guarantees the recorder landing a
    // window to fire in (David's b149 Intento B: 13s call, never foregrounded,
    // landing correctly waited on blocked_not_active and the call ended first).
    config.supportsVideo = true
    config.supportedHandleTypes = [.generic, .phoneNumber]
    let provider = CXProvider(configuration: config)
    provider.setDelegate(self, queue: nil)
    coldProvider = provider

    // ── Exit-reason telemetry (Sep 23 2026) ─────────────────────────────
    // Three calls died mid call on Sep 22 with JS heartbeats stopping about
    // 50 s after the app went to background and no crash in Sentry. JS cannot
    // report its own death, so the NATIVE side keeps a 5 s pulse in
    // UserDefaults (alive_at, app state, live CallKit calls, audio device
    // enabled, footprint, session category and route), stamps every lifecycle
    // edge (background, foreground, willTerminate, audio interruption, media
    // services reset), and subscribes to MetricKit so iOS itself tells us the
    // exit reasons (memory limit, watchdog, background task timeout, ...).
    // JS reads all of it through RNDeviceInfo.getCallAudioState on the next
    // launch and ships it on call_died_unreported and runtime_exit_reasons.
    startNativePulse()
    if #available(iOS 13.0, *) { MXMetricManager.shared.add(self) }
    let nc = NotificationCenter.default
    nc.addObserver(self, selector: #selector(onEnterBackground),
                   name: UIApplication.didEnterBackgroundNotification, object: nil)
    nc.addObserver(self, selector: #selector(onEnterForeground),
                   name: UIApplication.willEnterForegroundNotification, object: nil)
    nc.addObserver(self, selector: #selector(onWillTerminate),
                   name: UIApplication.willTerminateNotification, object: nil)
    nc.addObserver(self, selector: #selector(onAudioInterruption(_:)),
                   name: AVAudioSession.interruptionNotification, object: nil)
    nc.addObserver(self, selector: #selector(onMediaServicesReset),
                   name: AVAudioSession.mediaServicesWereResetNotification, object: nil)

    // The module subscribes lazily (~3s after first JS use) and iOS never replays
    // the early device-token notification — so re-emit the cached token on
    // becoming active and on a short timer until the module catches it.
    NotificationCenter.default.addObserver(
      self, selector: #selector(reemitToken),
      name: UIApplication.didBecomeActiveNotification, object: nil)
    // Race-free module-alive signal (posted by the patched Twilio module -init).
    NotificationCenter.default.addObserver(
      self, selector: #selector(moduleDidInit),
      name: Notification.Name("AttoTwilioModuleDidInit"), object: nil)
    reemitTimer = Timer.scheduledTimer(
      timeInterval: 1.0, target: self, selector: #selector(reemitTick),
      userInfo: nil, repeats: true)
  }

  @objc private func moduleDidInit() {
    moduleAlive = true
    NSLog("[AttoVoip] Twilio RN module alive")
    moduleDidInitHandoff()
  }

  // COLD-CALL HANDOFF (build 146). A call answered on the cold path lives only
  // in OUR heldCalls; the RN module's callMap is empty, so voice.getCalls()
  // returns nothing and JS renders ZERO in-call UI (no green header, no keypad,
  // no landing) — exactly what David hit on the b145 FASE 1A test. The patched
  // module subscribes to AttoColdCallHandoff BEFORE posting DidInit, and this
  // post is synchronous, so by the time -init returns the module's maps hold
  // the live call and the first JS getCalls() sees it. Extracted (b147) so the
  // callDidConnect SELF-HEAL can re-run it when a call is recovered after the
  // module already booted.
  private func moduleDidInitHandoff() {
    if !heldCalls.isEmpty {
      let fmt = ISO8601DateFormatter()
      var connectedAtISO: [String: String] = [:]
      for (k, d) in heldCallConnectedAt { connectedAtISO[k] = fmt.string(from: d) }
      var invitesForCalls: [String: TwilioVoice.CallInvite] = [:]
      for (k, _) in heldCalls { if let inv = heldInvites[k] { invitesForCalls[k] = inv } }
      NotificationCenter.default.post(
        name: Notification.Name("AttoColdCallHandoff"), object: nil,
        userInfo: [
          "calls": heldCalls,
          "invites": invitesForCalls,
          "connectedAt": connectedAtISO,
        ])
      UserDefaults.standard.set(heldCalls.count, forKey: "atto_cold_handoff_posted_count")
      mark("cold_handoff_posted")
    } else if callObserver.calls.contains(where: { $0.hasConnected && !$0.hasEnded }) {
      // ORPHAN DETECTOR (refined b148): only a CONNECTED live call with nothing
      // to hand off is an orphan. The b147 version also fired for a RINGING call
      // at module init — which is the NORMAL fast-boot order (module up before
      // the human answers), not a fault; that fire was the clue that exposed the
      // ordering bug, but as a permanent alarm it must mean "connected call
      // invisible to JS".
      mark("cold_handoff_empty_but_call_live")
    }
  }

  // Forward a cold call's lifecycle to the RN module (which re-emits it to JS as
  // its standard scopeCall events). The bootstrap stays the TVOCall delegate —
  // the delegate is fixed at accept — so without this bridge JS would never learn
  // the far end hung up and the in-call UI would stay stuck on a dead call.
  private func postColdCallEvent(_ type: String, call: TwilioVoice.Call, error: Error? = nil) {
    var info: [String: Any] = ["type": type]
    if let u = call.uuid?.uuidString { info["uuid"] = u }
    if let e = error as NSError? {
      info["errorCode"] = e.code
      info["errorMessage"] = e.localizedDescription
    }
    NotificationCenter.default.post(
      name: Notification.Name("AttoColdCallEvent"), object: nil, userInfo: info)
  }

  @objc private func reemitTick() {
    reemitCount += 1
    reemitToken()
    if reemitCount == 25 {
      reemitTimer?.invalidate()
      reemitTimer = Timer.scheduledTimer(
        timeInterval: 5.0, target: self, selector: #selector(reemitTick),
        userInfo: nil, repeats: true)
    }
  }

  @objc private func reemitToken() {
    guard let token = cachedToken else { return }
    postToken(token)
  }

  private func postToken(_ token: Data) {
    NotificationCenter.default.post(
      name: AttoVoipBootstrap.notificationName, object: nil,
      userInfo: [
        AttoVoipBootstrap.eventTypeKey: AttoVoipBootstrap.deviceTokenUpdated,
        AttoVoipBootstrap.deviceTokenKey: token,
      ])
  }

  // Native cold-launch telemetry: stamp a marker + timestamp into UserDefaults so
  // the next foreground can ship it to PostHog (and it shows in Console via NSLog).
  // Each marker is ALSO a Sentry breadcrumb: the native Sentry SDK is armed before
  // PushKit (withSentryNativeInit), so if anything in this path crashes, the crash
  // event carries the exact step sequence — no more black-box cold crashes.
  private func mark(_ event: String) {
    let ud = UserDefaults.standard
    ud.set(Date().timeIntervalSince1970, forKey: "atto_coldcallkit_\\(event)_at")
    NSLog("[AttoColdCallKit] \\(event)")
    #if canImport(Sentry)
    let crumb = Breadcrumb(level: .info, category: "cold_callkit")
    crumb.message = event
    SentrySDK.addBreadcrumb(crumb)
    #endif
  }

  // MARK: - PKPushRegistryDelegate

  func pushRegistry(_ registry: PKPushRegistry, didUpdate pushCredentials: PKPushCredentials, for type: PKPushType) {
    guard type == .voIP else { return }
    cachedToken = pushCredentials.token
    NSLog("[AttoVoip] device token received (\\(pushCredentials.token.count) bytes), emitting to RN module")
    postToken(pushCredentials.token)
  }

  func pushRegistry(
    _ registry: PKPushRegistry,
    didReceiveIncomingPushWith payload: PKPushPayload,
    for type: PKPushType,
    completion: @escaping () -> Void
  ) {
    guard type == .voIP else { completion(); return }

    let stateRaw = UIApplication.shared.applicationState.rawValue
    let appActive = UIApplication.shared.applicationState == .active
    let now = Date().timeIntervalSince1970
    UserDefaults.standard.set(now, forKey: "atto_last_voip_push_at")
    UserDefaults.standard.set(stateRaw, forKey: "atto_last_voip_push_appstate")
    NSLog("[AttoVoip] VoIP push appState=\\(stateRaw) active=\\(appActive) moduleAlive=\\(moduleAlive) coldDisabled=\\(coldDisabled)")

    // GUARANTEE completion exactly once, and never leave a push unhandled (an
    // unhandled push is redelivered by iOS and can jam the next launch).
    pendingPushCompletion = completion
    pushCompleted = false
    reportedThisPush = false
    inviteDecodedThisPush = false
    coldReportUUID = nil

    // Only a FOREGROUND-ACTIVE app can be trusted to report through the RN module
    // in time (and keep full in-app call controls). In ANY other state —
    // background, suspended, terminated — the module may be frozen and its report
    // would miss iOS's window: that is the crash. moduleAlive was the old, stale
    // signal that mis-routed a suspended-background wake into the warm path and
    // crashed anyway (Aug 13, build 141). applicationState is the real-time truth.
    if coldDisabled || (moduleAlive && appActive) {
      // This path posts to the RN module and re-posts up to ~12s while it boots
      // (only really needed when coldDisabled forces a true cold launch through
      // here). The backstop must sit just AFTER that ceiling so it never preempts
      // a legitimate late report.
      armHardDeadline(seconds: 13.0)
      recordReportOutcome("warm_pending", attempt: 0)
      UserDefaults.standard.set("warm", forKey: "atto_last_voip_report_path")
      deliverIncomingPush(payload.dictionaryPayload, attempt: 0)
      return
    }

    // Cold path reports to CallKit synchronously below (completion fires in well
    // under a second), so a SHORT backstop is right — it must fire before iOS's
    // ~5s kill, and only ever on a true hang.
    armHardDeadline(seconds: 4.0)

    // BULLETPROOF cold path: report a placeholder to CallKit RIGHT NOW, before any
    // decode, and complete INSIDE the report handler (Apple requires the report to
    // be registered before completion() returns — my first fix completed OUTSIDE
    // it and still crashed). The real caller name fills in a beat later when the
    // invite decodes. Nothing below can get us killed.
    UserDefaults.standard.set("cold", forKey: "atto_last_voip_report_path")
    mark("cold_push")
    let uuid = UUID()
    coldReportUUID = uuid
    let placeholder = CXCallUpdate()
    placeholder.remoteHandle = CXHandle(type: .generic, value: "Incoming call")
    placeholder.hasVideo = true // video-call trick: see supportsVideo note above
    coldProvider?.reportNewIncomingCall(with: uuid, update: placeholder) { [weak self] error in
      guard let self = self else { return }
      self.recordReportOutcome(error == nil ? "cold_reported" : "cold_report_error", attempt: 0)
      if let error = error { NSLog("[AttoColdCallKit] report failed: \\(error)") }
      self.completePush()
    }
    reportedThisPush = true

    // ENGINE PREINSTALL (b152). On a cold answer the media stack is created AT
    // ACCEPT with whatever audio device is installed at that instant, and WebRTC
    // forbids swapping it afterwards — so the injection engine could NEVER enter
    // a cold call's audio path (telemetry: install_returned_false at every cold
    // window; the transmit button then fails with "Couldn't send that into the
    // call"). This is the ONE moment where installing it is guaranteed safe on a
    // fresh process: before any decode/accept, no media stack exists. Gated on
    // the SAME persisted flag the module's -init reads; done via the module's
    // @try/@catch'd ObjC class method so a throw can never reach Swift (the b141
    // crash class); success judged by reading the installed device's class back.
    if UserDefaults.standard.bool(forKey: "atto_audio_injection_enabled") {
      // Swift.type: the handler parameter named type (PKPushType) shadows type(of:).
      let beforeCls = String(describing: Swift.type(of: TwilioVoiceSDK.audioDevice))
      if beforeCls == "AttoAudioEngineDevice" {
        mark("cold_engine_already_installed")
        // ENGINE RESET (Sep 13 2026). Telemetry over 14 days: every injection
        // that reached the far party ran on an engine installed fresh at THIS
        // push (cold_engine_preinstalled), and every silent one ran on a device
        // that was "already installed" from an earlier idle preinstall and had
        // been through a background cycle since. Its engines are stale by then
        // (file scheduled, player never enters playing, mix renders silence).
        // Tear the engines down here, before any media stack exists, so
        // startRendering rebuilds them at the live call rate exactly like a fresh
        // process does. teardownAudioEngine is an existing ObjC method on the
        // device; perform() keeps the call guarded at runtime.
        // Never touch the engines while a call is live (a second push during a
        // held cold call): tearing them down would silence the call in progress.
        let liveCall = !heldCalls.isEmpty ||
          callObserver.calls.contains(where: { $0.hasConnected && !$0.hasEnded })
        if liveCall {
          mark("cold_engine_reset_skipped_live_call")
        } else if let dev = TwilioVoiceSDK.audioDevice as? NSObject,
                  dev.responds(to: NSSelectorFromString("teardownAudioEngine")) {
          _ = dev.perform(NSSelectorFromString("teardownAudioEngine"))
          mark("cold_engine_reset")
        } else {
          mark("cold_engine_reset_unavailable")
        }
      } else if let engCls = NSClassFromString("AttoAudioEngineDevice") as? NSObject.Type,
                let modCls = NSClassFromString("TwilioVoiceReactNative") as? NSObject.Type,
                let dev = engCls.perform(NSSelectorFromString("sharedDevice"))?.takeUnretainedValue() {
        _ = modCls.perform(NSSelectorFromString("attoSetAudioDevice:"), with: dev)
        let afterCls = String(describing: Swift.type(of: TwilioVoiceSDK.audioDevice))
        mark(afterCls == "AttoAudioEngineDevice" ? "cold_engine_preinstalled" : "cold_engine_preinstall_failed")
      } else {
        mark("cold_engine_preinstall_unavailable")
      }
    }

    // Now decode. callInviteReceived UPDATES this same call with the real caller
    // (one call in CallKit, not two); cancelled ends it.
    let recognized = TwilioVoiceSDK.handleNotification(
      payload: payload.dictionaryPayload, delegate: self, delegateQueue: nil, callMessageDelegate: nil)
    if !inviteDecodedThisPush {
      NSLog("[AttoColdCallKit] no invite decoded yet (recognized=\\(recognized)); placeholder stands, auto-ends if it stays empty")
      DispatchQueue.main.asyncAfter(deadline: .now() + 6.0) { [weak self] in
        guard let self = self, !self.inviteDecodedThisPush, let u = self.coldReportUUID, u == uuid else { return }
        self.coldProvider?.reportCall(with: uuid, endedAt: nil, reason: .remoteEnded)
      }
    }
  }

  // Enable/disable the cold call's audio device to start/stop RTP. It may be a
  // DefaultAudioDevice (injection off) or the injection engine's custom
  // TVOAudioDevice (injection on) — both expose the ObjC enabled property. Use
  // the typed path when we can, else a guarded ObjC/KVC set, so we never assume the
  // concrete type (and never crash if a device somehow lacks the setter).
  private func setColdAudioEnabled(_ on: Bool) {
    if let d = coldAudioDevice as? TwilioVoice.DefaultAudioDevice {
      d.isEnabled = on
      return
    }
    // Injection's custom device (or any other TVOAudioDevice): set its ObjC
    // enabled property via KVC, guarded by responds(to:) so it can never throw an
    // unrecognized-selector exception. TVOAudioDevice objects are NSObjects.
    if let obj = coldAudioDevice as? NSObject, obj.responds(to: Selector("setEnabled:")) {
      obj.setValue(on, forKey: "enabled")
    }
  }

  // Arm the force-complete backstop. If nothing ever calls completePush() (every
  // report path silently failed), this fires so the PushKit handler still
  // completes — completing WITHOUT a reported call is itself a kill, so
  // forceCompletePush reports a short-lived placeholder first.
  private func armHardDeadline(seconds: Double) {
    let deadline = DispatchWorkItem { [weak self] in self?.forceCompletePush(reason: "hard_deadline") }
    hardDeadlineWork = deadline
    DispatchQueue.main.asyncAfter(deadline: .now() + seconds, execute: deadline)
  }

  // Idempotent completion — cancels the backstop and fires the PushKit completion
  // exactly once, no matter how many paths race to it.
  private func completePush() {
    hardDeadlineWork?.cancel()
    hardDeadlineWork = nil
    guard !pushCompleted else { return }
    pushCompleted = true
    if let c = pendingPushCompletion {
      pendingPushCompletion = nil
      c()
    }
  }

  // Last-resort backstop. If nothing was ever reported to CallKit, report a
  // short-lived placeholder FIRST (completing without a report is itself a kill),
  // then complete. Records the forced outcome for the next-launch telemetry.
  private func forceCompletePush(reason: String) {
    guard !pushCompleted else { return }
    recordReportOutcome("forced_\\(reason)", attempt: -1)
    if !reportedThisPush && !callKitHasLiveCall() {
      let uuid = UUID()
      let update = CXCallUpdate()
      update.remoteHandle = CXHandle(type: .generic, value: "Incoming call")
      update.hasVideo = true // video-call trick: see supportsVideo note above
      coldProvider?.reportNewIncomingCall(with: uuid, update: update) { [weak self] _ in
        DispatchQueue.main.asyncAfter(deadline: .now() + 6.0) {
          self?.coldProvider?.reportCall(with: uuid, endedAt: nil, reason: .remoteEnded)
        }
      }
    }
    completePush()
  }

  private func releasePendingCompletion() {
    completePush()
  }

  // MARK: - TwilioVoice.NotificationDelegate (cold-launch decode)

  func callInviteReceived(callInvite: TwilioVoice.CallInvite) {
    inviteDecodedThisPush = true
    // Correlation key: the SAME CallSid PostHog's call_* events carry. Stamped
    // here (native, pre-JS) so the next launch's telemetry and any Sentry crash
    // in this window can be joined to the exact Twilio call.
    UserDefaults.standard.set(callInvite.callSid, forKey: "atto_last_cold_call_sid")
    mark("cold_report")
    let update = buildUpdate(for: callInvite)
    if let uuid = coldReportUUID {
      // We ALREADY showed a placeholder call for this push. Fill it in with the
      // real caller name IN PLACE (reportCall(with:updated:)) — CallKit keeps
      // showing exactly ONE call, keyed by the UUID accept/end already reference.
      heldInvites[uuid.uuidString] = callInvite
      coldProvider?.reportCall(with: uuid, updated: update)
    } else {
      // No placeholder (e.g. warm path fell through) — report fresh and adopt the
      // SDK's own invite UUID as the call identity.
      coldReportUUID = callInvite.uuid
      heldInvites[callInvite.uuid.uuidString] = callInvite
      coldProvider?.reportNewIncomingCall(with: callInvite.uuid, update: update) { error in
        if let error = error { NSLog("[AttoColdCallKit] report failed: \\(error)") }
      }
    }
    reportedThisPush = true
    recordReportOutcome("cold_reported", attempt: 0)
    completePush()
  }

  func cancelledCallInviteReceived(cancelledCallInvite: TwilioVoice.CancelledCallInvite, error: Error) {
    mark("cold_cancelled")
    inviteDecodedThisPush = true
    // End the matching CallKit call. The invite may be keyed under the placeholder
    // UUID (updated in place) or its own UUID; match by callSid covers both.
    var ended = false
    for (uuidString, invite) in heldInvites where invite.callSid == cancelledCallInvite.callSid {
      if let uuid = UUID(uuidString: uuidString) {
        coldProvider?.reportCall(with: uuid, endedAt: nil, reason: .remoteEnded)
        ended = true
      }
      heldInvites.removeValue(forKey: uuidString)
    }
    // Cancel arrived before the invite decoded → no held invite yet. End the
    // placeholder we reported so it can't linger on screen.
    if !ended, let uuid = coldReportUUID {
      coldProvider?.reportCall(with: uuid, endedAt: nil, reason: .remoteEnded)
    }
    UserDefaults.standard.set(false, forKey: AttoVoipBootstrap.coldCallLiveKey)
    // A cancel push must still complete the PushKit handler.
    completePush()
  }

  private func buildUpdate(for callInvite: TwilioVoice.CallInvite) -> CXCallUpdate {
    var handleName = callInvite.from ?? "Unknown Caller"
    // Reproduce the SDK's @username handle: NSUserDefaults template +
    // customParameters substitution (getDisplayName in +CallKit.m).
    if let template = UserDefaults.standard.string(forKey: "incomingCallContactHandleTemplate"),
       !template.isEmpty {
      var processed = template
      for (key, value) in (callInvite.customParameters ?? [:]) {
        processed = processed.replacingOccurrences(of: "\${" + key + "}", with: value)
      }
      handleName = processed
    }
    let update = CXCallUpdate()
    update.remoteHandle = CXHandle(type: .generic, value: handleName)
    update.localizedCallerName = handleName
    update.supportsDTMF = true
    update.supportsHolding = true
    update.supportsGrouping = false
    update.supportsUngrouping = false
    update.hasVideo = true // video-call trick: see supportsVideo note above
    return update
  }

  private func callKitHasLiveCall() -> Bool {
    return callObserver.calls.contains { !$0.hasEnded }
  }

  // MARK: - Warm / feature-off path (unchanged, proven)

  // Report-window ceiling. Was 10 (~5s), which KILLED THE APP on cold launch: a
  // VoIP push to a terminated app must launch RN, boot JS and init the Twilio
  // module before anything can report to CallKit, and that regularly took longer
  // than 5s. completion() then fired with no call reported, so iOS terminated us
  // ("never posted an incoming call after a PushKit VoIP push", Sentry
  // NSInternalInconsistencyException x9 on b115) and throttled future VoIP
  // delivery — the client's "Larry is calling but it's not coming through".
  // 24 x 0.5s ~= 12s gives the cold-boot path room while staying inside iOS's
  // VoIP background window. atto_last_voip_report_* records the outcome.
  private static let maxDeliverAttempts = 24

  private func recordReportOutcome(_ outcome: String, attempt: Int) {
    UserDefaults.standard.set(outcome, forKey: "atto_last_voip_report_outcome")
    UserDefaults.standard.set(attempt, forKey: "atto_last_voip_report_attempt")
    UserDefaults.standard.set(Date().timeIntervalSince1970, forKey: "atto_last_voip_report_at")
  }

  private func deliverIncomingPush(_ payload: [AnyHashable: Any], attempt: Int) {
    if callKitHasLiveCall() {
      recordReportOutcome("reported", attempt: attempt)
      completePush()
      return
    }

    NotificationCenter.default.post(
      name: AttoVoipBootstrap.notificationName, object: nil,
      userInfo: [
        AttoVoipBootstrap.eventTypeKey: AttoVoipBootstrap.incomingPushReceived,
        AttoVoipBootstrap.incomingPushPayloadKey: payload,
      ])

    if callKitHasLiveCall() {
      recordReportOutcome("reported", attempt: attempt)
      completePush()
      return
    }

    if attempt >= AttoVoipBootstrap.maxDeliverAttempts {
      NSLog("[AttoVoip] VoIP push: CallKit never reported after \\(attempt) re-posts; releasing")
      recordReportOutcome("gave_up", attempt: attempt)
      completePush()
      return
    }

    DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) { [weak self] in
      self?.deliverIncomingPush(payload, attempt: attempt + 1)
    }
  }

  // MARK: - CXProviderDelegate (cold-launch answer/end/audio)

  func providerDidReset(_ provider: CXProvider) {
    setColdAudioEnabled(false)
  }

  func provider(_ provider: CXProvider, didActivate audioSession: AVAudioSession) {
    // Enabling the audio device is the ONLY thing that starts RTP — works for both
    // the DefaultAudioDevice (injection off) and the injection engine's device.
    setColdAudioEnabled(true)
    mark("cold_didActivate")
  }

  func provider(_ provider: CXProvider, didDeactivate audioSession: AVAudioSession) {
    setColdAudioEnabled(false)
    mark("cold_didDeactivate")
  }

  func provider(_ provider: CXProvider, perform action: CXAnswerCallAction) {
    mark("cold_answerAction")
    guard let invite = heldInvites[action.callUUID.uuidString] else {
      // Per-step markers (b147): the b146 field data showed cold_answerAction and
      // cold_connected stamped but cold_accept NOT — the handler diverged
      // somewhere in between and heldCalls stayed empty, killing the handoff.
      // These markers turn the next occurrence into an exact line number.
      mark("cold_answer_guard_failed")
      action.fail(); return
    }
    mark("cold_answer_guard_ok")
    // Give the call an RTP audio device WITHOUT ever re-assigning it. The SDK's
    // TwilioVoiceSDK.audioDevice is non-optional and already holds a usable device:
    // the SDK's own DefaultAudioDevice on a true cold launch (injection off), or the
    // audio-INJECTION engine's custom TVOAudioDevice (AttoAudioEngineDevice) when
    // injection is on. RE-ASSIGNING it after a media stack exists — which injection
    // builds at launch — throws TVOAudioDeviceMustBeSetBeforeMediaStackSetup, an
    // ObjC NSException that CANNOT be caught from Swift → a HARD CRASH (the client's
    // repeated b141 crash: Sentry REACT-NATIVE-4J, user 153 suicideking, injection
    // on). So NEVER set it here — adopt whatever is installed and just drive it via
    // setColdAudioEnabled on didActivate.
    coldAudioDevice = TwilioVoiceSDK.audioDevice
    UserDefaults.standard.set(true, forKey: AttoVoipBootstrap.coldCallLiveKey)

    // Adopt CallKit's UUID (== coldReportUUID, the one on screen) as the Twilio
    // Call identity so end/disconnect/report all reference the same call.
    let options = TwilioVoice.AcceptOptions(callInvite: invite) { builder in
      builder.uuid = action.callUUID
    }
    mark("cold_accept_begin")
    let call = invite.accept(options: options, delegate: self)
    heldCalls[action.callUUID.uuidString] = call
    mark("cold_accept")
    // ORDER-2 HANDOFF (b148, the ACTUAL b145/146/147 no-UI bug). RN boots FAST
    // (1.26s on David's phone) while a human answers at 5-8s — so the module was
    // already up when the call got accepted, the moduleDidInit handoff moment had
    // long passed (with nothing to hand off then: the call was still ringing),
    // and nobody ever handed the accepted call over. Post it RIGHT HERE.
    if moduleAlive { moduleDidInitHandoff() }
    action.fulfill()
  }

  // Observability for the CallKit action machinery itself: if a handler dies
  // mid-flight (e.g. an ObjC exception inside the SDK swallowed by CallKit's
  // transaction machinery), the unfulfilled action times out HERE — which is
  // otherwise invisible and leaves the answer half-done.
  func provider(_ provider: CXProvider, timedOutPerforming action: CXAction) {
    mark("cold_action_timeout")
    NSLog("[AttoColdCallKit] CXAction timed out: \\(type(of: action))")
    action.fulfill()
  }

  func provider(_ provider: CXProvider, perform action: CXEndCallAction) {
    if let call = heldCalls[action.callUUID.uuidString] {
      call.disconnect()
    } else if let invite = heldInvites[action.callUUID.uuidString] {
      invite.reject()
      heldInvites.removeValue(forKey: action.callUUID.uuidString)
    }
    UserDefaults.standard.set(false, forKey: AttoVoipBootstrap.coldCallLiveKey)
    action.fulfill()
  }

  func provider(_ provider: CXProvider, perform action: CXSetMutedCallAction) {
    if let call = heldCalls[action.callUUID.uuidString] {
      call.isMuted = action.isMuted
      action.fulfill()
    } else { action.fail() }
  }

  func provider(_ provider: CXProvider, perform action: CXSetHeldCallAction) {
    if let call = heldCalls[action.callUUID.uuidString] {
      call.isOnHold = action.isOnHold
      action.fulfill()
    } else { action.fail() }
  }

  func provider(_ provider: CXProvider, perform action: CXPlayDTMFCallAction) {
    if let call = heldCalls[action.callUUID.uuidString] {
      call.sendDigits(action.digits)
      action.fulfill()
    } else { action.fail() }
  }

  // MARK: - TwilioVoice.CallDelegate (cold call lifecycle)

  func callDidConnect(call: TwilioVoice.Call) {
    mark("cold_connected")
    if let uuid = call.uuid?.uuidString {
      heldCallConnectedAt[uuid] = Date()
      // SELF-HEAL (b147). On David's b146 test the answer handler died between
      // invite.accept and the heldCalls assignment (cold_accept never stamped),
      // so heldCalls stayed EMPTY and the module handoff had nothing to post —
      // zero in-call UI over a live call. This delegate callback carries the
      // live TVOCall itself, so re-register it here: the handoff (and everything
      // downstream — getCalls, JS adoption, UI) no longer depends on the accept
      // line having survived. Idempotent when accept completed normally.
      if heldCalls[uuid] == nil {
        heldCalls[uuid] = call
        mark("cold_call_recovered_at_connect")
      }
      // Re-post the handoff on EVERY connect when the module is up (b148): covers
      // the accept-path-death recovery AND the fast-boot order where the accept
      // handoff raced the module observer. Idempotent — the module overwrites the
      // same keys and JS dedups adoption per callSid.
      if moduleAlive {
        moduleDidInitHandoff()
      }
    }
    postColdCallEvent("connected", call: call)
  }

  func callDidDisconnect(call: TwilioVoice.Call, error: Error?) {
    postColdCallEvent("disconnected", call: call, error: error)
    finishColdCall(call)
  }

  func callDidFailToConnect(call: TwilioVoice.Call, error: Error) {
    NSLog("[AttoColdCallKit] cold call failed to connect: \\(error)")
    postColdCallEvent("connectFailure", call: call, error: error)
    finishColdCall(call)
  }

  func callIsReconnecting(call: TwilioVoice.Call, error: Error) {
    mark("cold_reconnecting")
    postColdCallEvent("reconnecting", call: call, error: error)
  }

  func callDidReconnect(call: TwilioVoice.Call) {
    mark("cold_reconnected")
    postColdCallEvent("reconnected", call: call)
  }

  private func finishColdCall(_ call: TwilioVoice.Call) {
    mark("cold_disconnected")
    coldProvider?.reportCall(with: call.uuid ?? UUID(), endedAt: nil, reason: .remoteEnded)
    if let uuid = call.uuid?.uuidString {
      heldCalls.removeValue(forKey: uuid)
      heldInvites.removeValue(forKey: uuid)
      heldCallConnectedAt.removeValue(forKey: uuid)
    }
    setColdAudioEnabled(false)
    UserDefaults.standard.set(false, forKey: AttoVoipBootstrap.coldCallLiveKey)
  }

  // CXCallObserverDelegate — we only read callObserver.calls synchronously.
  func callObserver(_ callObserver: CXCallObserver, callChanged call: CXCall) {}

  func pushRegistry(_ registry: PKPushRegistry, didInvalidatePushTokenFor type: PKPushType) {
    if type == .voIP { cachedToken = nil }
  }

  // MARK: - Exit-reason telemetry (native pulse + lifecycle edges)

  private var pulseTimer: Timer?

  private static let pulseKeys = [
    "alive_at", "app_state", "callkit_calls", "audio_enabled", "mem_mb", "audio_category",
    "cpu_pct", "avail_mb", "sys_free_mb", "cpu_top",
    "audio_output", "audio_input", "thermal", "low_power", "bg_at", "fg_at", "will_terminate_at",
    "interruption_began_at", "interruption_ended_at", "interruption_reason", "interruption_count",
    "media_reset_at",
  ]

  /// The pulse of the PREVIOUS process, copied before this process writes its
  /// first tick. Without this the launch overwrote the very values that say
  /// what the app looked like when it died (Sep 23 2026, first field run).
  private func snapshotPreviousPulse() {
    let ud = UserDefaults.standard
    for k in AttoVoipBootstrap.pulseKeys {
      if let v = ud.object(forKey: "atto_native_\\(k)") {
        ud.set(v, forKey: "atto_native_prev_\\(k)")
      } else {
        ud.removeObject(forKey: "atto_native_prev_\\(k)")
      }
    }
    ud.set(Date().timeIntervalSince1970, forKey: "atto_native_prev_snapshot_at")
  }

  private func startNativePulse() {
    snapshotPreviousPulse()
    pulseTimer?.invalidate()
    let t = Timer(timeInterval: 5.0, target: self, selector: #selector(nativePulse),
                  userInfo: nil, repeats: true)
    t.tolerance = 1.0
    RunLoop.main.add(t, forMode: .common)
    pulseTimer = t
    nativePulse()
  }

  @objc private func nativePulse() {
    let ud = UserDefaults.standard
    ud.set(Date().timeIntervalSince1970, forKey: "atto_native_alive_at")
    ud.set(UIApplication.shared.applicationState.rawValue, forKey: "atto_native_app_state")
    ud.set(callObserver.calls.filter { !$0.hasEnded }.count, forKey: "atto_native_callkit_calls")
    ud.set(AttoVoipBootstrap.audioDeviceEnabled(), forKey: "atto_native_audio_enabled")
    ud.set(AttoVoipBootstrap.footprintMB(), forKey: "atto_native_mem_mb")
    let session = AVAudioSession.sharedInstance()
    ud.set(session.category.rawValue, forKey: "atto_native_audio_category")
    ud.set(session.currentRoute.outputs.first?.portType.rawValue ?? "none",
           forKey: "atto_native_audio_output")
    ud.set(session.currentRoute.inputs.first?.portType.rawValue ?? "none",
           forKey: "atto_native_audio_input")
    ud.set(ProcessInfo.processInfo.thermalState.rawValue, forKey: "atto_native_thermal")
    ud.set(ProcessInfo.processInfo.isLowPowerModeEnabled, forKey: "atto_native_low_power")
    // CPU of THIS process since the last tick, as a percentage of one core, and
    // the memory picture: what this process may still take before its limit
    // and how much the whole device has free. MetricKit (Sep 23 2026) blamed
    // background exits on CPU limit and memory pressure; these say which.
    ud.set(AttoVoipBootstrap.cpuPercentSinceLastPulse(), forKey: "atto_native_cpu_pct")
    ud.set(Int(os_proc_available_memory() / (1024 * 1024)), forKey: "atto_native_avail_mb")
    ud.set(AttoVoipBootstrap.systemFreeMB(), forKey: "atto_native_sys_free_mb")
  }

  private static var lastCpuSeconds: Double = -1
  private static var lastCpuAt: Double = 0
  private static var lastThreadSeconds: [UInt64: Double] = [:]

  /// User plus system CPU time of every thread in the process, delta over the
  /// pulse interval, as percent of one core (100 = one core busy).
  private static func cpuPercentSinceLastPulse() -> Int {
    var threads: thread_act_array_t?
    var count = mach_msg_type_number_t(0)
    guard task_threads(mach_task_self_, &threads, &count) == KERN_SUCCESS, let list = threads else { return -1 }
    var total: Double = 0
    // Per thread too: the death report names the hog (Sep 23 2026, build 11:
    // 92 percent of a core in background, 54 s after the lock, and nothing
    // said which thread).
    var perThread: [(id: UInt64, name: String, seconds: Double)] = []
    for i in 0..<Int(count) {
      var info = thread_basic_info()
      var infoCount = mach_msg_type_number_t(MemoryLayout<thread_basic_info>.size / MemoryLayout<natural_t>.size)
      let kr = withUnsafeMutablePointer(to: &info) { ptr -> kern_return_t in
        ptr.withMemoryRebound(to: integer_t.self, capacity: Int(infoCount)) { raw in
          thread_info(list[i], thread_flavor_t(THREAD_BASIC_INFO), raw, &infoCount)
        }
      }
      if kr == KERN_SUCCESS && (info.flags & TH_FLAGS_IDLE) == 0 {
        let secs = Double(info.user_time.seconds) + Double(info.user_time.microseconds) / 1_000_000
          + Double(info.system_time.seconds) + Double(info.system_time.microseconds) / 1_000_000
        total += secs
        var ident = thread_identifier_info()
        var identCount = mach_msg_type_number_t(MemoryLayout<thread_identifier_info>.size / MemoryLayout<natural_t>.size)
        let kr2 = withUnsafeMutablePointer(to: &ident) { ptr -> kern_return_t in
          ptr.withMemoryRebound(to: integer_t.self, capacity: Int(identCount)) { raw in
            thread_info(list[i], thread_flavor_t(THREAD_IDENTIFIER_INFO), raw, &identCount)
          }
        }
        var name = "?"
        if let p = pthread_from_mach_thread_np(list[i]) {
          var buf = [CChar](repeating: 0, count: 64)
          if pthread_getname_np(p, &buf, buf.count) == 0 { name = String(cString: buf) }
        }
        if name.isEmpty { name = "thread" }
        perThread.append((id: kr2 == KERN_SUCCESS ? ident.thread_id : UInt64(i), name: name, seconds: secs))
      }
    }
    let size = vm_size_t(UInt(count) * UInt(MemoryLayout<thread_t>.size))
    vm_deallocate(mach_task_self_, vm_address_t(bitPattern: list), size)
    let now = Date().timeIntervalSince1970
    let elapsed = now - lastCpuAt
    if lastCpuSeconds >= 0 && elapsed > 0 {
      var tops: [(String, Int)] = []
      for t in perThread {
        let prev = lastThreadSeconds[t.id] ?? t.seconds
        let pct = Int(((t.seconds - prev) / elapsed) * 100)
        if pct >= 3 { tops.append((t.name, pct)) }
      }
      tops.sort { $0.1 > $1.1 }
      let top = tops.prefix(4).map { "\\($0.0):\\($0.1)" }.joined(separator: ",")
      UserDefaults.standard.set(top, forKey: "atto_native_cpu_top")
    }
    var next: [UInt64: Double] = [:]
    for t in perThread { next[t.id] = t.seconds }
    lastThreadSeconds = next
    defer { lastCpuSeconds = total; lastCpuAt = now }
    if lastCpuSeconds < 0 || elapsed <= 0 { return -1 }
    return Int(((total - lastCpuSeconds) / elapsed) * 100)
  }

  /// Free plus inactive pages on the device, in MB (what iOS can hand out
  /// before it starts evicting background apps).
  private static func systemFreeMB() -> Int {
    var stats = vm_statistics64()
    var count = mach_msg_type_number_t(MemoryLayout<vm_statistics64>.size / MemoryLayout<integer_t>.size)
    let kr = withUnsafeMutablePointer(to: &stats) { ptr -> kern_return_t in
      ptr.withMemoryRebound(to: integer_t.self, capacity: Int(count)) { raw in
        host_statistics64(mach_host_self(), HOST_VM_INFO64, raw, &count)
      }
    }
    if kr != KERN_SUCCESS { return -1 }
    let page = UInt64(vm_kernel_page_size)
    let free = (UInt64(stats.free_count) + UInt64(stats.inactive_count)) * page
    return Int(free / (1024 * 1024))
  }

  private static func audioDeviceEnabled() -> Bool {
    let device = TwilioVoiceSDK.audioDevice
    if let d = device as? TwilioVoice.DefaultAudioDevice { return d.isEnabled }
    // Injection's custom device: read its ObjC enabled flag through KVC, guarded.
    if let obj = device as? NSObject, obj.responds(to: NSSelectorFromString("isEnabled")) {
      return (obj.value(forKey: "enabled") as? Bool) ?? false
    }
    return false
  }

  private static func footprintMB() -> Int {
    var info = task_vm_info_data_t()
    var count = mach_msg_type_number_t(MemoryLayout<task_vm_info_data_t>.size) / 4
    let kr = withUnsafeMutablePointer(to: &info) { ptr -> kern_return_t in
      ptr.withMemoryRebound(to: integer_t.self, capacity: Int(count)) { raw in
        task_info(mach_task_self_, task_flavor_t(TASK_VM_INFO), raw, &count)
      }
    }
    if kr != KERN_SUCCESS { return -1 }
    return Int(info.phys_footprint / (1024 * 1024))
  }

  @objc private func onEnterBackground() {
    UserDefaults.standard.set(Date().timeIntervalSince1970, forKey: "atto_native_bg_at")
    nativePulse()
  }

  @objc private func onEnterForeground() {
    UserDefaults.standard.set(Date().timeIntervalSince1970, forKey: "atto_native_fg_at")
    nativePulse()
  }

  @objc private func onWillTerminate() {
    UserDefaults.standard.set(Date().timeIntervalSince1970, forKey: "atto_native_will_terminate_at")
    nativePulse()
  }

  @objc private func onAudioInterruption(_ n: Notification) {
    let ud = UserDefaults.standard
    let typeRaw = (n.userInfo?[AVAudioSessionInterruptionTypeKey] as? UInt) ?? 99
    if typeRaw == AVAudioSession.InterruptionType.began.rawValue {
      ud.set(Date().timeIntervalSince1970, forKey: "atto_native_interruption_began_at")
      let reason = (n.userInfo?[AVAudioSessionInterruptionReasonKey] as? UInt) ?? 99
      ud.set(Int(reason), forKey: "atto_native_interruption_reason")
    } else {
      ud.set(Date().timeIntervalSince1970, forKey: "atto_native_interruption_ended_at")
    }
    ud.set(ud.integer(forKey: "atto_native_interruption_count") + 1,
           forKey: "atto_native_interruption_count")
    NSLog("[AttoExit] audio interruption type=%lu", typeRaw)
  }

  @objc private func onMediaServicesReset() {
    UserDefaults.standard.set(Date().timeIntervalSince1970, forKey: "atto_native_media_reset_at")
    NSLog("[AttoExit] media services were reset")
  }
}

// MetricKit: the operating system's own account of why the app exited. Metric
// payloads arrive at most once a day, diagnostics on the next launch after a
// crash or hang. Both are stored as JSON for JS to ship.
@available(iOS 13.0, *)
extension AttoVoipBootstrap: MXMetricManagerSubscriber {
  func didReceive(_ payloads: [MXMetricPayload]) {
    guard let p = payloads.last else { return }
    var d: [String: Any] = [:]
    d["begin"] = p.timeStampBegin.timeIntervalSince1970
    d["end"] = p.timeStampEnd.timeIntervalSince1970
    d["payloads"] = payloads.count
    if #available(iOS 14.0, *), let ex = p.applicationExitMetrics {
      let f = ex.foregroundExitData
      let b = ex.backgroundExitData
      d["fg_normal"] = f.cumulativeNormalAppExitCount
      d["fg_memory_limit"] = f.cumulativeMemoryResourceLimitExitCount
      d["fg_watchdog"] = f.cumulativeAppWatchdogExitCount
      d["fg_bad_access"] = f.cumulativeBadAccessExitCount
      d["fg_abnormal"] = f.cumulativeAbnormalExitCount
      d["fg_illegal_instruction"] = f.cumulativeIllegalInstructionExitCount
      d["bg_normal"] = b.cumulativeNormalAppExitCount
      d["bg_memory_limit"] = b.cumulativeMemoryResourceLimitExitCount
      d["bg_memory_pressure"] = b.cumulativeMemoryPressureExitCount
      d["bg_watchdog"] = b.cumulativeAppWatchdogExitCount
      d["bg_task_assertion_timeout"] = b.cumulativeBackgroundTaskAssertionTimeoutExitCount
      d["bg_cpu_limit"] = b.cumulativeCPUResourceLimitExitCount
      d["bg_locked_file"] = b.cumulativeSuspendedWithLockedFileExitCount
      d["bg_bad_access"] = b.cumulativeBadAccessExitCount
      d["bg_abnormal"] = b.cumulativeAbnormalExitCount
      d["bg_illegal_instruction"] = b.cumulativeIllegalInstructionExitCount
    }
    if let m = p.memoryMetrics {
      d["peak_mem_mb"] = Int(m.peakMemoryUsage.converted(to: .megabytes).value)
    }
    if let json = try? JSONSerialization.data(withJSONObject: d),
       let str = String(data: json, encoding: .utf8) {
      UserDefaults.standard.set(str, forKey: "atto_metrickit_exits_json")
      UserDefaults.standard.set(Date().timeIntervalSince1970, forKey: "atto_metrickit_received_at")
      NSLog("[AttoExit] MetricKit exits: %@", str)
    }
  }

  @available(iOS 14.0, *)
  func didReceive(_ payloads: [MXDiagnosticPayload]) {
    var crashes: [[String: Any]] = []
    var hangs = 0
    for p in payloads {
      for c in p.crashDiagnostics ?? [] {
        var e: [String: Any] = [:]
        e["signal"] = c.signal?.intValue ?? -1
        e["exception_type"] = c.exceptionType?.intValue ?? -1
        e["exception_code"] = c.exceptionCode?.intValue ?? -1
        e["termination_reason"] = c.terminationReason ?? ""
        e["vm_region"] = c.virtualMemoryRegionInfo ?? ""
        e["end"] = p.timeStampEnd.timeIntervalSince1970
        crashes.append(e)
      }
      hangs += p.hangDiagnostics?.count ?? 0
    }
    let d: [String: Any] = ["crashes": crashes, "hangs": hangs, "payloads": payloads.count]
    if let json = try? JSONSerialization.data(withJSONObject: d),
       let str = String(data: json, encoding: .utf8) {
      UserDefaults.standard.set(str, forKey: "atto_metrickit_diag_json")
      UserDefaults.standard.set(Date().timeIntervalSince1970, forKey: "atto_metrickit_diag_received_at")
      NSLog("[AttoExit] MetricKit diagnostics: %@", str)
    }
  }
}
`;

module.exports = function withTwilioVoipPushRegistry(config) {
  return withAppDelegate(config, (cfg) => {
    if (cfg.modResults.language !== 'swift') {
      throw new Error(
        `[withTwilioVoipPushRegistry] Expected a Swift AppDelegate, got "${cfg.modResults.language}".`
      );
    }

    let src = cfg.modResults.contents;
    if (src.includes('AttoVoipBootstrap')) return cfg; // already patched

    // 1) PushKit / UIKit / CallKit / TwilioVoice imports.
    if (!src.includes('import PushKit')) {
      if (!src.includes(IMPORT_ANCHOR)) {
        throw new Error(
          '[withTwilioVoipPushRegistry] Could not find the import anchor — AppDelegate template changed.'
        );
      }
      src = src.replace(IMPORT_ANCHOR, IMPORT_INJECT);
    }

    // 2) Retained property so the registry delegate is not deallocated.
    if (!src.includes(PROPERTY_ANCHOR)) {
      throw new Error(
        '[withTwilioVoipPushRegistry] Could not find the reactNativeFactory property anchor — AppDelegate template changed.'
      );
    }
    src = src.replace(PROPERTY_ANCHOR, PROPERTY_INJECT);

    // 3) Create + start the bootstrap first thing in didFinishLaunching.
    const afterInit = src.replace(
      /(didFinishLaunchingWithOptions[^\n]*\n\s*\) -> Bool \{\n)/,
      `$1${INIT_BLOCK}`
    );
    if (afterInit === src) {
      throw new Error(
        '[withTwilioVoipPushRegistry] Could not find didFinishLaunchingWithOptions to inject the bootstrap — AppDelegate template changed.'
      );
    }
    src = afterInit;

    // 3b) iOS memory-warning hook. Fires BEFORE jetsam terminates the app and
    // runs on a system callback that survives a frozen JS thread, so it is the
    // earliest signal on the OOM path that silently killed calls. Stamped to
    // NSUserDefaults; JS reports it as `call_memory_warning`. Injected only if
    // the AppDelegate doesn't already override it.
    if (!src.includes('applicationDidReceiveMemoryWarning')) {
      const afterMem = src.replace(
        /(\n\s*\/\/ Linking API\n)/,
        `\n${MEMORY_WARNING_OVERRIDE}$1`
      );
      if (afterMem === src) {
        // Fall back to injecting before the final closing brace of the class.
        const lastBrace = src.lastIndexOf('\n}');
        if (lastBrace !== -1) {
          src = `${src.slice(0, lastBrace)}\n${MEMORY_WARNING_OVERRIDE}${src.slice(lastBrace)}`;
        }
      } else {
        src = afterMem;
      }
    }

    // 4) Append the native helper class to the same file.
    src = `${src.trimEnd()}\n${BOOTSTRAP_CLASS}`;

    cfg.modResults.contents = src;
    return cfg;
  });
};
