const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Xcode 26.x's clang rejects fmt 11's consteval format strings whenever the
 * `fmt` pod is compiled from scratch (Sep 23 2026, local preview build):
 *
 *   call to consteval function 'fmt::basic_format_string<...>' is not a
 *   constant expression   (Pods/fmt/include/fmt/format-inl.h)
 *
 * Earlier builds only passed because DerivedData still held fmt objects
 * compiled by an older toolchain. Defining FMT_CONSTEVAL empty is the
 * upstream workaround: fmt compiles its format strings as plain constexpr
 * and nothing changes at runtime. The Podfile is regenerated by prebuild, so
 * the setting has to be injected here, inside react_native_post_install's
 * block, rather than edited in ios/Podfile.
 */
const MARKER = '# withFmtConsteval';
const INJECT = `
    ${MARKER}: Xcode 26 rejects fmt 11's consteval strings, see plugins/withFmtConsteval.js
    installer.pods_project.targets.each do |target|
      next unless target.name == 'fmt'
      target.build_configurations.each do |config|
        flags = Array(config.build_settings['OTHER_CPLUSPLUSFLAGS'] || ['$(inherited)'])
        flags << '-DFMT_CONSTEVAL=' unless flags.include?('-DFMT_CONSTEVAL=')
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] = flags
      end
    end
`;

module.exports = function withFmtConsteval(config) {
  return withDangerousMod(config, [
    'ios',
    (cfg) => {
      const podfile = path.join(cfg.modRequest.platformProjectRoot, 'Podfile');
      let src = fs.readFileSync(podfile, 'utf8');
      if (src.includes(MARKER)) return cfg;
      const anchor = 'post_install do |installer|\n';
      if (!src.includes(anchor)) {
        throw new Error('[withFmtConsteval] post_install block not found in the Podfile');
      }
      src = src.replace(anchor, anchor + INJECT);
      fs.writeFileSync(podfile, src);
      return cfg;
    },
  ]);
};
