const { withAppDelegate } = require('@expo/config-plugins');

/**
 * withTwilioVoipPushRegistry
 * --------------------------
 * Owns the app's single VoIP `PKPushRegistry` natively, from process launch,
 * so an incoming call survives a cold launch from a terminated state AND the
 * Twilio React-Native SDK still receives its device token reliably.
 *
 * The problem this solves
 * -----------------------
 * `@twilio/voice-react-native-sdk`'s native module (`TwilioVoiceReactNative`)
 * learns its PushKit device token by *observing* an `NSNotification`
 * (`TwilioVoicePushRegistryNotification` / `deviceTokenUpdated`) that a
 * `PKPushRegistry` delegate posts. In the stock SDK that delegate is created
 * by `voice.initializePushRegistry()` from JS — which is far too late for a
 * cold launch (iOS gives a VoIP app only a few seconds after a push to call
 * `reportNewIncomingCall`, killing it with a FrontBoard `0xBAADCA11` watchdog
 * termination otherwise — observed in production, see project_larry_incident).
 *
 * The previous attempt at fixing this created a bare native registry in the
 * AppDelegate but DROPPED `voice.initializePushRegistry()`. That broke
 * registration entirely: iOS delivers the device-token credentials very early
 * (before the RN bridge — and therefore the SDK module — exists), the module
 * is not yet subscribed, and `NSNotificationCenter` does NOT replay missed
 * notifications. So `self.deviceTokenData` in the module stayed nil forever and
 * every `voice.register()` rejected with "Failed to initialize PushKit device
 * token" (Sentry REACT-NATIVE-3P) — no incoming calls at all.
 *
 * The fix
 * -------
 * Keep a SINGLE registry (no second `PKPushRegistry`, no double push handling)
 * owned by a small native bootstrap created in `didFinishLaunchingWithOptions`.
 * It caches the device token the moment iOS delivers it and RE-EMITS the
 * SDK's notification — on `didBecomeActive` and on a short repeating timer —
 * until the SDK module (which subscribes lazily on first JS use, ~3 s after
 * launch) has had a chance to observe it. Re-emitting is idempotent: the
 * module just overwrites the same token. Incoming pushes are forwarded live to
 * the same notification the SDK already listens for.
 *
 * This project uses CNG (`ios/` is git-ignored and regenerated by
 * `expo prebuild` / EAS), so the AppDelegate must be patched via this plugin
 * rather than edited directly. The native helper class is appended to
 * `AppDelegate.swift` itself, so no new source file has to be linked into the
 * Xcode project.
 *
 * NOTE (coordinated JS expectation): the JS side must NOT call
 * `voice.initializePushRegistry()` — that would stand up a SECOND
 * `PKPushRegistry` and double-handle every push. See
 * `front/src/hooks/useTwilioVoice.ts`.
 */

const IMPORT_ANCHOR = 'import ReactAppDependencyProvider\n';
const IMPORT_INJECT =
  'import ReactAppDependencyProvider\nimport PushKit\nimport UIKit\nimport CallKit\n';

const PROPERTY_ANCHOR = 'var reactNativeFactory: RCTReactNativeFactory?\n';
const PROPERTY_INJECT =
  'var reactNativeFactory: RCTReactNativeFactory?\n\n  var attoVoipBootstrap: AttoVoipBootstrap?\n';

const INIT_BLOCK = [
  "    // Bring up the VoIP PushKit registry before anything else so the push",
  '    // delegate is alive from launch: it caches the device token (re-emitting',
  "    // it to Twilio's RN module once that module subscribes) and forwards",
  '    // incoming pushes — the cold-start path that avoids the FrontBoard',
  '    // 0xBAADCA11 watchdog kill. See withTwilioVoipPushRegistry.',
  '    let bootstrap = AttoVoipBootstrap()',
  '    bootstrap.start()',
  '    attoVoipBootstrap = bootstrap',
  '',
].join('\n');

const BOOTSTRAP_CLASS = `

/// Single, launch-owned VoIP \`PKPushRegistry\` for the Twilio Voice RN SDK.
/// See withTwilioVoipPushRegistry.js for the full rationale.
final class AttoVoipBootstrap: NSObject, PKPushRegistryDelegate, CXCallObserverDelegate {
  // These string constants must match @twilio/voice-react-native-sdk's
  // TwilioVoicePushRegistry.m exactly — the SDK module observes this exact
  // notification name / keys to learn its device token and incoming pushes.
  private static let notificationName = Notification.Name("TwilioVoicePushRegistryNotification")
  private static let eventTypeKey = "type"
  private static let deviceTokenUpdated = "deviceTokenUpdated"
  private static let deviceTokenKey = "deviceToken"
  private static let incomingPushReceived = "incomingPushReceived"
  private static let incomingPushPayloadKey = "incomingPushPayload"

  private var voipRegistry: PKPushRegistry?
  private var cachedToken: Data?
  private var reemitTimer: Timer?
  private var reemitCount = 0
  // System-wide CallKit observer: lets us detect synchronously when the Twilio
  // SDK has actually reported the incoming call, so we stop re-posting the push
  // and release the PushKit completion.
  private let callObserver = CXCallObserver()

  func start() {
    let registry = PKPushRegistry(queue: .main)
    registry.delegate = self
    registry.desiredPushTypes = [.voIP]
    voipRegistry = registry

    // Begin observing system CallKit state so deliverIncomingPush can tell when
    // the SDK has reported the call.
    callObserver.setDelegate(self, queue: .main)

    // The SDK module subscribes only when JS first touches it (after launch),
    // and iOS does not replay the early device-token notification — so we
    // re-emit the cached token when the app becomes active and on a short
    // timer until the module has had a chance to catch it.
    NotificationCenter.default.addObserver(
      self,
      selector: #selector(reemitToken),
      name: UIApplication.didBecomeActiveNotification,
      object: nil
    )
    reemitTimer = Timer.scheduledTimer(
      timeInterval: 1.0,
      target: self,
      selector: #selector(reemitTick),
      userInfo: nil,
      repeats: true
    )
  }

  @objc private func reemitTick() {
    reemitCount += 1
    reemitToken()
    // The first 25 ticks fire every 1s to catch a quick relaunch. But the
    // Twilio TurboModule subscribes lazily on the first getVoice() call,
    // which on a fresh login / OTP flow can land well after that burst —
    // and iOS never replays the early device-token notification. So after
    // the burst we drop to a slow cadence and KEEP re-emitting for the
    // app's lifetime: whenever the module finally subscribes it gets the
    // token within ~5s. Re-emitting a cached token is free once the module
    // already has it (it just re-sets the same value, no JS event).
    if reemitCount == 25 {
      reemitTimer?.invalidate()
      reemitTimer = Timer.scheduledTimer(
        timeInterval: 5.0,
        target: self,
        selector: #selector(reemitTick),
        userInfo: nil,
        repeats: true
      )
    }
  }

  @objc private func reemitToken() {
    guard let token = cachedToken else { return }
    postToken(token)
  }

  private func postToken(_ token: Data) {
    NotificationCenter.default.post(
      name: AttoVoipBootstrap.notificationName,
      object: nil,
      userInfo: [
        AttoVoipBootstrap.eventTypeKey: AttoVoipBootstrap.deviceTokenUpdated,
        AttoVoipBootstrap.deviceTokenKey: token,
      ]
    )
  }

  // MARK: - PKPushRegistryDelegate

  func pushRegistry(
    _ registry: PKPushRegistry,
    didUpdate pushCredentials: PKPushCredentials,
    for type: PKPushType
  ) {
    guard type == .voIP else { return }
    cachedToken = pushCredentials.token
    NSLog("[AttoVoip] device token received (\\(pushCredentials.token.count) bytes), emitting to RN module")
    postToken(pushCredentials.token)
  }

  func pushRegistry(
    _ registry: PKPushRegistry,
    didReceiveIncomingPushWith payload: PKPushPayload,
    for type: PKPushType,
    completion: @escaping () -> Void
  ) {
    guard type == .voIP else { completion(); return }

    // Telemetry: the one native vantage point on a cold launch. appState
    // tells us whether the RN bridge had any chance to be alive (active /
    // background / inactive) when the push hit. Visible live in Console.app
    // / Xcode device logs (filter "AttoVoip"); also stamped into
    // UserDefaults so the next foreground can compute push→handle latency.
    let state = UIApplication.shared.applicationState.rawValue
    let now = Date().timeIntervalSince1970
    UserDefaults.standard.set(now, forKey: "atto_last_voip_push_at")
    UserDefaults.standard.set(state, forKey: "atto_last_voip_push_appstate")
    NSLog("[AttoVoip] VoIP push received appState=\\(state) at=\\(now) payload=\\(payload.dictionaryPayload)")

    // iOS requires the SDK's reportNewIncomingCall to run BEFORE completion(),
    // or it kills the app and throttles future VoIP pushes. The SDK reports
    // only inside its module's synchronous handler for our notification — and
    // on a suspended / cold-launched app that module isn't alive yet, so a
    // single post is lost (NSNotificationCenter never replays it). Re-post on a
    // short cadence until CallKit actually shows the call (proof the SDK
    // reported it), holding completion() open meanwhile. The synchronous
    // CallKit check before each re-post means an already-alive module
    // (foreground) handles exactly one post and we return immediately — and we
    // never feed the same push to a live module twice.
    deliverIncomingPush(payload.dictionaryPayload, attempt: 0, completion: completion)
  }

  private func callKitHasLiveCall() -> Bool {
    return callObserver.calls.contains { !$0.hasEnded }
  }

  private func deliverIncomingPush(
    _ payload: [AnyHashable: Any],
    attempt: Int,
    completion: @escaping () -> Void
  ) {
    if callKitHasLiveCall() {
      completion()
      return
    }

    NotificationCenter.default.post(
      name: AttoVoipBootstrap.notificationName,
      object: nil,
      userInfo: [
        AttoVoipBootstrap.eventTypeKey: AttoVoipBootstrap.incomingPushReceived,
        AttoVoipBootstrap.incomingPushPayloadKey: payload,
      ]
    )

    // The post is synchronous: a live module has already reported to CallKit.
    if callKitHasLiveCall() {
      completion()
      return
    }

    // ~5s ceiling (10 × 0.5s). Past this iOS may terminate us regardless;
    // releasing the push is no worse than the previous immediate completion().
    if attempt >= 10 {
      NSLog("[AttoVoip] VoIP push: CallKit never reported after \\(attempt) re-posts; releasing")
      completion()
      return
    }

    DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) { [weak self] in
      self?.deliverIncomingPush(payload, attempt: attempt + 1, completion: completion)
    }
  }

  // CXCallObserverDelegate — required to start observing; we only read
  // \`callObserver.calls\` synchronously, so there's nothing to do on change.
  func callObserver(_ callObserver: CXCallObserver, callChanged call: CXCall) {}

  func pushRegistry(
    _ registry: PKPushRegistry,
    didInvalidatePushTokenFor type: PKPushType
  ) {
    if type == .voIP { cachedToken = nil }
  }
}
`;

module.exports = function withTwilioVoipPushRegistry(config) {
  return withAppDelegate(config, (cfg) => {
    if (cfg.modResults.language !== 'swift') {
      throw new Error(
        `[withTwilioVoipPushRegistry] Expected a Swift AppDelegate, got "${cfg.modResults.language}".`
      );
    }

    let src = cfg.modResults.contents;
    if (src.includes('AttoVoipBootstrap')) return cfg; // already patched

    // 1) PushKit / UIKit imports.
    if (!src.includes('import PushKit')) {
      if (!src.includes(IMPORT_ANCHOR)) {
        throw new Error(
          '[withTwilioVoipPushRegistry] Could not find the import anchor — AppDelegate template changed.'
        );
      }
      src = src.replace(IMPORT_ANCHOR, IMPORT_INJECT);
    }

    // 2) Retained property so the registry delegate is not deallocated.
    if (!src.includes(PROPERTY_ANCHOR)) {
      throw new Error(
        '[withTwilioVoipPushRegistry] Could not find the reactNativeFactory property anchor — AppDelegate template changed.'
      );
    }
    src = src.replace(PROPERTY_ANCHOR, PROPERTY_INJECT);

    // 3) Create + start the bootstrap first thing in didFinishLaunching.
    const afterInit = src.replace(
      /(didFinishLaunchingWithOptions[^\n]*\n\s*\) -> Bool \{\n)/,
      `$1${INIT_BLOCK}`
    );
    if (afterInit === src) {
      throw new Error(
        '[withTwilioVoipPushRegistry] Could not find didFinishLaunchingWithOptions to inject the bootstrap — AppDelegate template changed.'
      );
    }
    src = afterInit;

    // 4) Append the native helper class to the same file (no new source file
    //    to link into the Xcode project).
    src = `${src.trimEnd()}\n${BOOTSTRAP_CLASS}`;

    cfg.modResults.contents = src;
    return cfg;
  });
};
