import type { FeedPost } from '@/types/post';

// TODO: re-upload ad videos to Cloudinary and restore entries
export const DEMO_ADS: FeedPost[] = [
/*
  {
    id: 'ad-demo-4',
    type: 'ad',
    isAd: true,
    videoUrl:
      'https://res.cloudinary.com/dxzcutnlp/video/upload/v1774929698/ssstik.io__apple_1774929444222_nddtf3.mp4',
    author: {
      id: 0,
      username: 'apple',
      displayName: 'Apple',
      avatar: 'https://img.icons8.com/ios-filled/200/ffffff/mac-os.png',
      isFollowing: false,
    },
    description: 'Think Different',
    likesCount: 8417,
    commentsCount: 521,
    sharesCount: 347,
    repostsCount: 189,
    isLiked: false,
    isBookmarked: false,
    isReposted: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
  {
    id: 'ad-demo-3',
    type: 'ad',
    isAd: true,
    videoUrl:
      'https://res.cloudinary.com/dxzcutnlp/video/upload/v1774928437/ssstik.io__rangerover_1774928424114_ywcgtd.mp4',
    author: {
      id: 0,
      username: 'rangerover',
      displayName: 'Range Rover',
      avatar: 'https://img.icons8.com/color/200/land-rover.png',
      isFollowing: false,
    },
    description: 'Above and Beyond',
    likesCount: 3712,
    commentsCount: 198,
    sharesCount: 156,
    repostsCount: 72,
    isLiked: false,
    isBookmarked: false,
    isReposted: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
  },
  {
    id: 'ad-demo-1',
    type: 'ad',
    isAd: true,
    videoUrl:
      'https://res.cloudinary.com/dxzcutnlp/video/upload/v1774927846/ssstik.io__nike_1774926551658_hpimh7.mp4',
    author: {
      id: 0,
      username: 'nike',
      displayName: 'Nike',
      avatar: 'https://img.icons8.com/ios-filled/200/ffffff/nike.png',
      isFollowing: false,
    },
    description: 'JustDoit',
    likesCount: 2841,
    commentsCount: 134,
    sharesCount: 89,
    repostsCount: 47,
    isLiked: false,
    isBookmarked: false,
    isReposted: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: 'ad-demo-2',
    type: 'ad',
    isAd: true,
    videoUrl:
      'https://res.cloudinary.com/dxzcutnlp/video/upload/v1774928304/ssstik.io__mcdonalds_1774928255843_kugoso.mp4',
    author: {
      id: 0,
      username: 'mcdonalds',
      displayName: "McDonald's",
      avatar: 'https://img.icons8.com/color/200/mcdonalds.png',
      isFollowing: false,
    },
    description: "I'm lovin' it",
    likesCount: 5203,
    commentsCount: 312,
    sharesCount: 201,
    repostsCount: 98,
    isLiked: false,
    isBookmarked: false,
    isReposted: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
*/];
